### ISSUE TITLE
Incorrect extruder steps for G2/G3 moves at low extruder steps/mm 

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#1006]
In RRF 3.5.1 use the following minimum configuration of a 6XD:

M83
G90
M569 P0.0 S1 R1
M569 P0.1 S1 R1
M569 P0.2 S1 R1
M569 P0.0 T3:3:1:1
M584 X0.0 Y0.1 E0.2 
M92 X80 Y80 E5
M566 X10000.00 Y1000.00 E100000 
M203 X48000.00 Y48000.00 E100000
M201 X10000.00 Y10000.00 E100000 
M563 P0 S"test" D0 
T0

Then send the following commands:

G92 X20 Y20
G3 X20 I-5 J0 E10 F1000

The pattern of pulses in not smooth, and the number of pulses is not correct.
![image](https://github.com/Duet3D/RepRapFirmware/assets/1642947/25683987-b964-4f31-b2ea-0e28d7ba1e8d)

Setting M92 E400 resolves the issue;

**Comment by dc42** [comment]
Fixed in 3.5-dev for both main boards and expansion boards. Issue also affects 3.4 and earlier firmware versions.
