### ISSUE TITLE
Simple filament presence switch on mainboard with extruder on expansion board: pin not allocated correctly

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#1014]
When allocating a simple switch based filament presence sensor, if the switch is on a mainboard and the extruder is on an expansion board the board address part of the pin allocation is stripped out, so the allocation is always attempted on the expansion board:

to reproduce:
```
M591 D0 P0

M591 D0
Extruder 0 has no filament sensor

M591 D0 P1 C"0.io3.in" S2

M591 D0
Simple filament sensor on pin 20.io3.in, enabled always, output low when no filament, filament present: yes
```

if a invalid pin (for the expansion board, valid for the mainboard is chosen:

```
M591 D0 P1 C"0.io5.in" S2
Error: M591: Unknown pin name 'io5.in
```

**Comment by dc42** [comment]
Fixed in 3.5-dev source code. Fix tested by Tony.
