### ISSUE TITLE
axis_minima and axis_maxima declarations

### ISSUE THREAD

**Issue by dnewman-polar3d** [dc42/RepRapFirmware#102]
The axis_minima and axis_maxima declarations in Platform.h need to use a macro.  As is, they fail for  case when MAX_AXES is less than six.

E.g., perhaps in Pins_xxx.h define, for example,

    #define MOTION_DRIVES_(a,b,c,d,e,f) { a, b, c, d }

Then use that in Platform.h?

**Comment by dnewman-polar3d** [comment]
... and also in GCodes.cpp

    const char GCodes::axisLetters[MAX_AXES] = MOTION_DRIVES_( 'X', 'Y', 'Z', 'U', 'V', 'W' );
    
    const char* const PAUSE_G = "pause.g";
    const char* const HomingFileNames[MAX_AXES] = MOTION_DRIVES_( "homex.g", "homey.g", "homez.g", "homeu.g", "homev.g", "homew.g" );

**Comment by dc42** [comment]
Fixed in 1.19beta2.
