### ISSUE TITLE
M581 does not throw an error in SBC mode when incorrect P parameter is used

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#1022]
Minor issue in SBC mode:

`M581 P"io2.in" T2`
does not throw an error

@dc42 commented:
" I just checked the code. In SBC mode the parameter value defaults to 0 if not given"

**Comment by dc42** [comment]
Fix committed to 3.6-dev source. Should be tested in 3.6.-alpha.2.

**Comment by dc42** [comment]
Back ported to 3.5-dev for release in 3.5.3.
