### ISSUE TITLE
Feature Request:  G-Code Files - Date uploaded & sorting

### ISSUE THREAD

**Issue by RichWP** [dc42/RepRapFirmware#103]
Hello,
It would be great if the 'G-Code Files' tab in the web Interface allowed sorting by the column headers.  It would also be nice if it displayed the date a file was uploaded, and allowed sorting on this field as well.
Thanks.

**Comment by dc42** [comment]
Please request this feature at https://github.com/chrishamm/DuetWebControl/issues.
