### ISSUE TITLE
[3.6-dev] Modbus Frame Delay Issues

### ISSUE THREAD

**Issue by benagricola** [dc42/RepRapFirmware#1034]
FAO @dc42

Testing the Modbus code as it stands in 3.6-dev using the following macro:

```
    ; Read spindle state bitmap
    M261.1 P1 A1 F3 R4097 B1 V"spindleInputState"

    ; Read requested frequency
    M261.1 P1 A1 F3 R4098 B1 V"currentFrequency"

    ; Read the output frequency, current, voltage
    M261.1 P1 A1 F3 R4099 B1 V"spindleOutputState"

    echo { var.spindleInputState }
    echo { var.currentFrequency }
    echo { var.spindleOutputState }
```

I would quite consistently get `no or bad response from Modbus device` from the second or third `M261.1` call, unless I added `G4 P1` between each call.

The code [currently calculates](https://github.com/Duet3D/RepRapFirmware/blob/d474e339d528b30901ddeaa2847968e02f95239f/src/Comms/AuxDevice.cpp#L360) a frame delay of 4 characters, which gets rounded down to 2ms at 38400bps (the configuration on my UART). 

The `delay` function documentation says `The actual delay may be up to 1 millisecond less than this, or arbitrarily greater.`  - and I think in my case this is consistently coming up at less than 1ms, for example:

![low_delay](https://github.com/user-attachments/assets/4009a0f9-2015-4947-88b7-95416af56c17)

This shows the delay between the end of the reply from the initial command, and the start of the request for the second command - which is actually _less_ than 1ms.

The [legacy modbus spec](https://www.modbus.org/docs/PI_MBUS_300.pdf) seems to suggest that for baud rates over 19200 a static frame delay should be used of at least 1.75ms, but this isn't mentioned at all in the most recent spec.

Either way, if I add +1 to the calculated frame delay to account for it possibly waiting 1ms less than expected, it always works.

**Comment by dc42** [comment]
Thanks for your report. It seems odd that a delay(2) call could end up delaying less than 1ms. Anyway, I've added another 1 to the value that CalcTransmissionTime returns.
