### ISSUE TITLE
This repo not in sync with DuetWiFiSocketServer repo?

### ISSUE THREAD

**Issue by dnewman-polar3d** [dc42/RepRapFirmware#104]
Looks like MessageFormats.h in the DuetWiFiSocketServer is out of date with more recent checkins here in RepRapFirmware?  Likely commits missing to the latter, DuetWiFiSocketServer?

The RepRapFirmware source file DuetNG/DuetWiFi/Network.cpp

1. Uses a field named "protocol" in the ListenOrConnectData structure. However, the present MessageFormats.h in DuetWiFiSocketServer doesn't declare that field in that structure.
2. Expects a "diagnostics" value in the enum NetworkCommand. However, the present MessageFormats.h in DuetWiFiSocketServe doesn't declare that value in that enum.

So something is out of sync somewhere it would seem.

**Comment by dc42** [comment]
Should be OK now.
