### ISSUE TITLE
[Bug]: G30 S0 completes, but with error

### ISSUE THREAD

**Issue by droftarts** [dc42/RepRapFirmware#1046]
See forum thread: https://forum.duet3d.com/topic/36605/bug-using-g30-s0-inside-homez-g-fails

G30 S0 appears to function the same as G30 or G30 S-4, but generates an error such as `Error: Number of calibration factors (0) not equal to number of leadscrews (4)` or `Error: This kinematics does not support auto-calibration`. It seems G30 S0 is interpreted by the firmware as having a P parameter, and causes the error messages, even though the actual probing/homing completes successfully. G30, G30 S0 and G30 S-4 and lower should be synonymous.

@dc42 said: The entry at https://docs.duet3d.com/en/User_manual/Reference/Gcodes#g30-single-z-probe says that G30 S0 or S-4 or lower without a P parameter do a normal probe and set the Z height. The default S parameter is -4. I'll change it so that if S >= 0 and there is no P parameter then we set S to -4. That should fix it.

**Comment by dc42** [comment]
Fixed in 3.6-dev (before 3.6.0-beta.1 release) and 3.5-dev (after 3.5.3 release).
