### ISSUE TITLE
Simulation doesn't complete in RRF 3.5.3

### ISSUE THREAD

**Issue by dc42** [dc42/RepRapFirmware#1049]
See https://forum.duet3d.com/topic/36656/last-update-3-5-3-file-simulation-runs-infinitely.

**Comment by dc42** [comment]
Caused by this commit https://github.com/Duet3D/RepRapFirmware/commit/16f5a74ac7987f2e29f4d9f666696ede4dfcb473#diff-b19f2962c4061527d96f673ae218934300f9f66d68a895bf820d66f9bc60d22eR4442. Reinstated the missing line in 3.5-dev source code.

**Comment by EagleB3** [comment]
After installing the new MB6HC binary from the link you provided on the forum, the problem was completely resolved. THANK YOU SO MUCH!
![link on the forum](https://github.com/user-attachments/assets/e63e07b9-7aa5-4aa2-b91c-40a42b804840)

**Comment by T3P3** [comment]
confirmed fixed.
