### ISSUE TITLE
[Bug]: Heater feedforward is broken in 3.6.0-beta.1 and 3.6.0 alpha versions

### ISSUE THREAD

**Issue by droftarts** [dc42/RepRapFirmware#1051]
See forum thread: https://forum.duet3d.com/topic/36738/3-6-0-beta-1-heater-feedforward-not-working/

Confirmed by @dc42:
> The whole motion system was rewritten in 3.6 to support the new IS algorithm. The code that contains the call to action feedforward no longer exists and doesn't have a direct replacement. It's the call to Tool::ApplyFeedforward that is missing.

**Comment by dc42** [comment]
Fixed in 3.6 beta 2.
