### ISSUE TITLE
I want to use CNC and placement machine functions. I have an STM32 motherboard, model: Manta M8P v2.0+CB1. How should I compile the running firmware or system that supports this motherboard?

### ISSUE THREAD

**Issue by mayjack0312** [dc42/RepRapFirmware#1055]
### Is your feature request related to a problem? Please describe.

I want to use CNC and placement machine functions. I have an STM32 motherboard, model: Manta M8P v2.0+CB1. How should I compile the running firmware or system that supports this motherboard?

### Describe the solution you propose.

The main control of the motherboard is: `STM32H723ZET6`, how should I transplant it correctly?

**Comment by T3P3** [comment]
Please discuss this on the forum, In the STM section:
https://forum.duet3d.com/category/36/stm

**Comment by jaysuk** [comment]
This board isn't supported by the STM32 port so it won't work

**Comment by mayjack0312** [comment]
> Please discuss this on the forum, In the STM section: https://forum.duet3d.com/category/36/stm

OK, thank you for your reply

**Comment by mayjack0312** [comment]
> This board isn't supported by the STM32 port so it won't work

Okay, then I will try other firmwares, thank you for your reply
