### ISSUE TITLE
[bug]: RRF 3.5.3 - Extruder drives on mainboard-as-expansion-board not moving

### ISSUE THREAD

**Issue by droftarts** [dc42/RepRapFirmware#1058]
https://forum.duet3d.com/topic/36794/issue-with-secondary-extruder-drive-on-can-bus-with-mini5plus

This issue appears to be fixed in 3.6.0-beta.1, but not in 3.5.3.

**Comment by T3P3** [comment]
as its fixed in 3.6 and not a quick fix in 3.5 we are proposing not to do this unless further users require it that cannot use 3.6
