### ISSUE TITLE
Object Model Reporting issues with CAN connected Expansion boards - "unsupported type code 24"

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#1059]
_Only checked in SBC mode thus far._
Impacts 3.6.beta1 and 3.6.beta2 (other versions not checked)
Various OM keys within boards[] do not report correctly for expansion boards. e.g:
```
boards[1].firmwareDate
boards[1].firmwareFileName
boards[1].firmwareVersion
boards[1].name
boards[1].shortName
```
In all cases these report:
`unsupported type code 24`

Other keys **_do_** report correctly, e.g.:
```
boards[1].drivers[0].status
boards[1].uniqueId
boards[1].state
```

**Work around:**
Appending an empty string to the query/use of the result works:

e.g.
```
echo (boards[1].firmwareVersion^"")
global firmwareVersionTB = (boards[1].firmwareVersion^"")
```

**Comment by dc42** [comment]
Works OK for me in standalone mode:

```
echo boards[1].firmwareVersion
3.6.0-beta.2
echo boards[1].firmwareFileName
Duet3Firmware_EXP3HC.bin
echo boards[3].firmwareVersion
3.6.0-beta.1+1
echo boards[4].firmwareFileName
Duet3Firmware_SZP.bin
```
The "unsupported type code" message comes from file DataTransfer.cpp so it SBC-specific. The full list of expression type codes is defined in file ObjectMode/TypeCode.h. TypeCode::CanExpansionBoardDetails is code 24. I think the code in DataTransfer just needs to call ExpressionValue::ExtractRequestedPart to handle this case.

**Comment by chrishamm** [comment]
That's right, TypeCode::CanExpansionBoardDetails wasn't supported in `DataTransfer.cpp`. My fix looks a bit different but it works as well - the underlying code calls `ExtractRequestedPart`, too. Please merge it into `3.5-dev` and `3.6-dev`.
