### ISSUE TITLE
Thermostatic fan control not working for H101

### ISSUE THREAD

**Issue by notnyt** [dc42/RepRapFirmware#107]
M106 P2 T60 H101 logic seems to be broken and ends up running the fan continuously regardless of the temperature. 

M106 P2
Fan2 frequency: 250Hz, speed: 100%, min: 10%, blip: 0.10, inverted: no, trigger: 60C, heaters: 101

I confirm the behavior works normal for this when using H1 and H100

RepRapFirmware for Duet WiFi version 1.19beta2 running on Duet WiFi 1.0

**Comment by notnyt** [comment]
Is the TMC2660 temperature only reporting as 0, 100, or 150?

**Comment by notnyt** [comment]
11.3 Overtemperature Detection
The TMC2660 integrates a two-level temperature sensor (100°C warning and 150°C shutdown) for diagnostics and for protection of the power MOSFETs

**Comment by dc42** [comment]
Yes.

**Comment by notnyt** [comment]
That would explain why any value I entered for T ran the fan....

**Comment by dc42** [comment]
The operands of the <= operator at lines 2107 and 2119 of Platform.cpp should be reversed. Will fix in next beta.
