### ISSUE TITLE
Grid compensation not working (1.19beta2)

### ISSUE THREAD

**Issue by Alex9779** [dc42/RepRapFirmware#108]
Hi,
so I got another issue now as my machine is nearly finished.
I did a grid compensation run, all parameters seem fine, the heightmap is generated and looks ok. I have to do some manual leveling so but for now its ok.
But I thought after the run the leveling is active. Though no matter how I move a head, manually (panel or web), with the console (panel or web) or with a file the Z axis does not move.
I have deviations of about 0.3mm at max so I think I have to notice some movement. But there is any...
I did G29 S1 again and again but the Z does not move.
Did I miss something again?

**Comment by Alex9779** [comment]
So I reverted to 1.18.1 and there without doing anything else I just move X around with the panel Z axis moves and compensates...

**Comment by dc42** [comment]
Thanks for the report. Bug confirmed, and I am just testing the fix in 1.19beta3.
