### ISSUE TITLE
Extrusion issue after pause

### ISSUE THREAD

**Issue by notnyt** [dc42/RepRapFirmware#111]
Printing with extrusion in relative mode (M83 in gcode) and sending a pause from the paneldue

pause.g does not contain M82 or M83

Running G1 E-4 F3600 in pause.g causes a retraction which runs for quite some time, apparently going back to -4 as if it were in absolute mode

**Comment by dc42** [comment]
Where did your pause.g file come from? I updated all the pause.g files in my github repo to include the M83 in August 2015.

**Comment by notnyt** [comment]
made from scratch, works fine with M83 in there, just strange it changes mode when running pause.  If not worth looking at feel free to close

**Comment by dc42** [comment]
Each gcode source has its own relative/absolute extrusion state. That state defaults to absolute extrusion, unless you include M83 in your config.g file. The state at the start of pause.g will be the state associated with whatever input source commanded the pause, i.e. web, PanelDue or USB.

I'd prefer to default the state to relative extrusion, but most slicers use absolute extrusion by default, so doing that would probably cause more users to request support.

**Comment by notnyt** [comment]
The issue was that even if the gcode source sets M83, then when pause is called, it goes back to absolute.

**Comment by dc42** [comment]
Perhaps I didn't make myself clear. The SD card is a separate gcode source.

**Comment by notnyt** [comment]
Oh, understood, thanks.

**Comment by Eddiiie** [comment]
Ohhh is this why I cannot use Cura with DuetWifi/RRF/diamond head?

Only Slic3r works.   The extruders just grind grind grind never see so much filament come out at once.

What a mess.



________________________________

**Comment by dc42** [comment]
Sounds like you included M83 in your config.g file AND you forgot to include M82 in your Cura start gcode.
