### ISSUE TITLE
DuetWifiFirmware1.19beta7

### ISSUE THREAD

**Issue by Eddiiie** [dc42/RepRapFirmware#114]
I applied this firmware through the WebUI.
Wifi no longer works.
Console on PanelDue says WiFi Module started Error: Failed to initiaise WiFi module code -10

How to fix?

**Comment by dc42** [comment]
If you upgraded from 1.18.2 or earlier, see https://duet3d.com/wiki/DuetWiFiFirmware_1.19beta.

**Comment by Eddiiie** [comment]
I pushed a button on the DuetWifi with a USB cable connected.
It said installing device driver for Bossic Port or something.
Then your reply came in.
I copied files to the SD card as mentioned.
Panel Due says "Connecting"

Computer connected via USB cable now says unrecognized device.

dammit

**Comment by dc42** [comment]
So you pressed the Erase button, and now you need to re-install main firmware using SAM-BA or Bossac 1,.8. See the wiki.

**Comment by Eddiiie** [comment]
Really?  Thanks for the help.

**Comment by Eddiiie** [comment]
SAM-BA has a list of a bunch of boards, Wiki does not help with this.

**Comment by Eddiiie** [comment]
ok I got it.. Fallback 3 -   https://duet3d.com/wiki/Updating_main_firmware
