### ISSUE TITLE
IDEX U axis when tool is selected moves "X" too (1.19beta7)

### ISSUE THREAD

**Issue by Alex9779** [dc42/RepRapFirmware#117]
Hi,
I tried the new 1.19beta7 because I had tooloffset problems with 1.19beta6.
But now when I switch to tool 1, moving X moves both carriages to the desired point resulting in a carriage crash...

**Comment by dc42** [comment]
I'll look into it. What  M563 tool definitions do you have, and what commands do you have in your tool change files?

**Comment by dc42** [comment]
Problem confirmed, and fixed in release 1.19beta8.

**Comment by Alex9779** [comment]
Short test confirmed the fix in 1.19beta8...
