### ISSUE TITLE
Improvement for the firmware retraction

### ISSUE THREAD

**Issue by zlowred** [dc42/RepRapFirmware#142]
Long story short. I used the first result that comes up in Google to set up firmware retraction in Simplify3D (http://thrinter.com/using-firmware-retraction-with-simplify3d/). I've set up retraction in S3D as 1mm, 30mm/s, 0 extra-unretract, 0 z-lift. I also configured my firmware retraction as 1mm retract @ 50mm/s + unretract @ 25mm/s and 0.5mm z-lift. Somehow, I misread the part of the manual saying that first retraction in Simplify3D happens at 30% speed as "1/3 speed". So I ended up with the GCode that starts with the normal retraction at 1/3 speed without z-lift followed by firmware unretract which crashed the hot nozzle into my build surface (by the z-lift amount set up in firmware retraction).
The simple solution here would be to keep track of the G10/G11 commands and allow unretract only if retract has happened before.

**Comment by dc42** [comment]
The code that processes G10/G11 already does that. To use firmware retraction in S3D wirth RRF, all you need to do is to check "Include M101/M102/M03 commands" in the G-Code settings of S3D.
