### ISSUE TITLE
Cannot Print Files With Parenthesis 

### ISSUE THREAD

**Issue by Alfaa123** [dc42/RepRapFirmware#149]
Any files with a parenthesis in it's filename will fail to print with a "File Not Found" error.

Removing the parenthesis solves the issue. Problem occured after update allowing parenthesis in gcode commands, so I believe the parenthesis is acting as an escape character and the inputs were not sanitized.

**Comment by dc42** [comment]
In standard GCode, anything in parentheses is a comment, so it is ignored. In firmware 1.20, in any command that take a filename or other string parameter, you can enclose that parameter in double quotation marks. This allows you use use spaces, parentheses, semicolons etc. in filenames.

**Comment by Alfaa123** [comment]
Oh, of course.

But when printing from a PanelDue or the web interface, it simply fails with no explanation.

Obviously, this isn't a super important issue, but I simply figured I'd try and contribute where I can.

**Comment by dc42** [comment]
It's fixed in the current PanelDue beta firmware,
