### ISSUE TITLE
Inverted logic for deprecated M27?

### ISSUE THREAD

**Issue by dcnewman** [dc42/RepRapFirmware#15]
Whilst deprecated, there is still code for M27 (SD status) in GCodes.cpp and it appears to be inverted?

	case 27: // Report print status - Deprecated
		if (!reprap.GetPrintMonitor()->IsPrinting())
		{
			reply.copy("SD printing.\n");
		}
		else

So if IsPrinting() is false, then the response is "SD printing".

**Comment by dc42** [comment]
Thanks, will be fixed in next version 1.09m.
