### ISSUE TITLE
Make it clear how to find the firmware!

### ISSUE THREAD

**Issue by dintid** [dc42/RepRapFirmware#154]
When going to https://github.com/dc42/RepRapFirmware there is no way to navigate to the newest firmware. Only option is to open EdgeRelease (and some other folders).
The only way to find the link to newest firmware is to google and then open https://duet3d.com/wiki/Where_to_get_Duet_firmware_and_tools and click the link to ->
https://github.com/dc42/RepRapFirmware/releases

Why isn't the folder "releases" available directly in the repository?

**Comment by dc42** [comment]
It is. When you are at the root of the repository, you will see a line of links with these captions:

 976 commits    6 branches    6 releases    14 contributors    GPL-3.0

Click on 'releases'.

**Comment by dintid** [comment]
![image](https://user-images.githubusercontent.com/4258031/34565958-0d47d43a-f15d-11e7-90e0-5d765dd8ef48.png)
oh, I would never had figured that one. Maybe make a link to it as well.
