### ISSUE TITLE
SerialComunication

### ISSUE THREAD

**Issue by dasquiddi** [dc42/RepRapFirmware#156]
I've tried to get a Serial Connection with my DuetWifi board but hadn't success at all.

My Setup:
- USB-to-Serial TTL    <-->  DuetWifi Board via PanelDue Header (RX, TX, GND)
- Baud set to 57600 as mentioned in the blog
-  last Firmware on DuetWifi

Did i have to enable the comunication somewhere in the Settings or does anyone has some suggestions for me?

**Comment by dc42** [comment]
Please ask support questions on the Duet3d forum.
