### ISSUE TITLE
1.21RC3 Prints do not start. Duet Ethernet.

### ISSUE THREAD

**Issue by Alfaa123** [dc42/RepRapFirmware#163]
Updated our testing machine to 1.21RC3 this morning. Unfortunately we didn't get far as we encountered a major bug in this release.

Upon starting a print, every heater starts to warm up. Once they get to proper temperature, they just... turn off again. No error messages or anything. Print stays at 0% complete indefinitely. Printer is not locked up, you can still pause and cancel the prints, they just never actually start.

 Downgraded immediately to 1.21RC2 and the problem went away.

**Comment by dc42** [comment]
Did you amend the homing files as described in the upgrade notes, and check that homing works?

On 28 February 2018 21:43:32 GMT+00:00, Alexander Elder <notifications@github.com> wrote:
>Updated our testing machine to 1.21RC3 this morning. Unfortunately we
>didn't get far as we encountered a major bug in this release.
>
>Upon starting a print, every heater starts to warm up. Once they get to
>proper temperature, they just... turn off again. No error messages or
>anything. Print stays at 0% complete indefinitely. Printer is not
>locked up, you can still pause and cancel the prints, the just never
>actually start.
>
> Downgraded immediately to 1.21RC2 and the problem went away.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dc42/RepRapFirmware/issues/163

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Alfaa123** [comment]
Aha, I got a little too excited and must have skipped over that part. I believe this is exactly what the issue is. Thank you!

**Comment by dc42** [comment]
I'm glad you solved it; however there should have been an error message in the GCode Console page of DWC when the homing sequence was aborted.

**Comment by Alfaa123** [comment]
Looking at the console on the PanelDue, an error was generated there, but it didn't get passed to DWC.

**Comment by dc42** [comment]
Thanks, I'll test this. If the homing command came from the SD card print file then a message should have been written to both PanelDue and DWC. Whereas if you sent a homing command manually from PanelDue or DWC, the message would be written only to the device you sent the command from.
