### ISSUE TITLE
Blinking Auto-Bed-Compensation button

### ISSUE THREAD

**Issue by Christoph13524** [dc42/RepRapFirmware#165]
Hi,

my Auto-Bed-Compensation button is blinking every 3 seconds in my macOS Safari browser (version 11.1) in the way the screenshot shows. It is not blinking in Chrome browser! 
1.21RC5
![1](https://user-images.githubusercontent.com/37507127/37566693-0bdb0826-2abd-11e8-9864-d9299fce4ec7.png)

**Comment by JohnOCFII** [comment]
I've also seen different behavior in Safari compared to Chrome on my Mac.  While I do most of my web browsing in Safari, I've decided to just use Chrome for DWC.

**Comment by Kriechi** [comment]
This is the repository for the main firmware.
The issue tracker for DWC is over at https://github.com/chrishamm/DuetWebControl

/cc @chrishamm

**Comment by Christoph13524** [comment]
Ah ok sorry, didn't know that! Next time I'll do it right.
