### ISSUE TITLE
Speed Percentage not shown, as German Word is too wide for Button width on PanelDue 7i

### ISSUE THREAD

**Issue by tobiasvogel** [dc42/RepRapFirmware#171]
The German translation for the word "Speed" is "Geschwindigkeit" - and as such is too wide for the Button-Width on the PanelDue 7i, so the percentage is basically hidden.
One can in fact set the Printing-Speed blindly so this is not a bug as such, however it will never present you with a number.

**Comment by dc42** [comment]
Already fixed in the latest release.
