### ISSUE TITLE
Getting recurring error on latest firmware - Error: M32: Cannot set file to print, because a file is already being printed

### ISSUE THREAD

**Issue by jgrouse** [dc42/RepRapFirmware#199]
After updating the firmware, if I inadvertently cause an error such as starting a job after one is already started, cancel the first job and then start a new one, it appears to not clear the first error and keeps logging the following message every 15 sec while the new job is running.  
 
File xxxxx.gcode selected for printing
Error: M32: Cannot set file to print, because a file is already being printed
Resume-after-power-fail state saved
Error: Attempting to extrude with no tool selected.
Printing paused
Cancelled printing file xxxxxx.gcode, print time was 0h 1m

As soon as the job finishes it stops logging these however they come back when I start the next job.  It's like it is not clearing those errors after showing them for the first time.

**Comment by T3P3** [comment]
please can you use the duet 3d forum for support:
https://forum.duet3d.com/category/6/firmware-installation

**Comment by dc42** [comment]
And please state which firmware version you are using in your forum post.
