### ISSUE TITLE
short-to-ground frequently

### ISSUE THREAD

**Issue by gnydick** [dc42/RepRapFirmware#202]
I'm using this code on the M3D Promega. I've two Duet Maestro boards, both exhibit the same behavior. Two situations, but generate short-to-ground

1) extruder is experiencing a lot of resistance and triggers short-to-ground error. I'm guessing this is a misnomer and is not actually a short-to-ground

2) I've replaced my single Z motor with a dual-Z lead screw design and I frequently get short-to-ground when making movements, like homing Z. Again, I think this is a misnomer and more of a resistance detection, again, happens on both Maestros.

Is this tunable and can we get a more correct error message?

**Comment by dc42** [comment]
Please ask firmware support questions on the forum at duet3d.com, not here.

**Comment by gnydick** [comment]
ok
