### ISSUE TITLE
web control throws error with every g-code manually entered

### ISSUE THREAD

**Issue by gnydick** [dc42/RepRapFirmware#203]
Version: 1.22
Message: Uncaught TypeError: rememberedGCodes.indexOf is not a function
URL: http://192.168.1.200/js/dwc.js
Line: 1175:69
Error object: {}

this happens every time i use the g-code console or the quick enter box at the top of the screen

Firmware Name: | RepRapFirmware for Duet 2 Maestro
-- | --
Duet Maestro 1.0
2.01(RTOS) (2018-07-26b2)
1.22

**Comment by dc42** [comment]
This is not an issue in RepRapFirmware, it is a known bug in Duet Web Control when upgrading from earlier versions, and the workaround has been described several times on the Duet3D forum.
