### ISSUE TITLE
error: 'delay' was not declared in this scope

### ISSUE THREAD

**Issue by tkstreet** [dc42/RepRapFirmware#222]
Build Configurations:
CoreNG: SAM3X8E (master, cfd95bdca063a8eac0006dce013d6e104482d5b8)
RepRapFirmware: Duet085 (master, b29378abe0e5d9608e73f32d07c6871616f5fd28)

When attempting to build, the following errors occur:

`../src/Storage/MassStorage.cpp:83:13: error: 'delay' was not declared in this scope`
and
`../src/Storage/FileStore.cpp:295:25: error: 'micros' was not declared in this scope`

It doesn't appear that asf/common/services/delay is included in this RepRapFirmware build configuration.  As for the second error, I can't figure it out.

**Comment by leolongvu** [comment]
Hello

Can I ask how you solved this problem?
