### ISSUE TITLE
Macro and Filament Sensor

### ISSUE THREAD

**Issue by NightlyFidelis** [dc42/RepRapFirmware#224]
Hello,

i've a Duet Wifi and a filament sensor.
Is it possible to load a Macro for exemple named "load_filament" to load the filament ?
Like the Prusa MK3 wich the sensor see filament and engage the extruder.

I Load my filament with the Macro filament, but i apreciate if this is automatic :)

regards

**Comment by dc42** [comment]
Please use https://forum.duet3d.com for support requests.
