### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by SijieLiang** [dc42/RepRapFirmware#227]
Hello dc42,

I just imported and tried to compile the CoreNG project, but there was an error:

make: *** No rule to make target 'clean'.  Stop.	

Then I just tried to compile other projects, which are FreeRTOS and RRFLibraries, and the same errors occurred.

Just wonder how can I fix it.

Sincerely.

**Comment by SijieLiang** [comment]
btw, I did this on the Linux platform.

**Comment by dc42** [comment]
This is not an issue, it is a support question. Ask it on the support forum at duet3d.com.
