### ISSUE TITLE
12864 Display - All Current Tool Values are 0

### ISSUE THREAD

**Issue by incogizmo** [dc42/RepRapFirmware#229]
The menu items 079, 179 and 279 are displaying 0 rather than the current tool values.

I have checked by updating a menu and reloading the menu, 000, 100, 200 and 001, 101, 201 all report the temperatures as expected.
Using 2.02RC3 while printing and Tool 1 is active.

**Comment by dc42** [comment]
https://github.com/dc42/RepRapFirmware#support-issues-and-suggestions
