### ISSUE TITLE
Roland.h and related files not checked in?

### ISSUE THREAD

**Issue by dcnewman** [dc42/RepRapFirmware#23]
RepRapFirmware.h has references to Roland.h and a type defined by it.  However, Roland.h appears nowhere in the repository.

**Comment by dcnewman** [comment]
Looks like Pins.h wasn't checked in either.

**Comment by dc42** [comment]
Sorry about that. I've now checked in Pins.h, Roland.h and Roland.cpp.

David Crocker, Escher Technologies Ltd.
http://www.eschertech.com
Tel. +44 (0)20 8144 3265 or +44 (0)7977 211486

**Comment by dcnewman** [comment]
Looks like they haven't been sync'd up to the publicly visible github repo?  At least, I do not yet see those three files in the dev branch.  (Nor the master branch --  I know it's obsolete, but I checked there just in case.)

**Comment by dc42** [comment]
Sorry, I must have forgotten to sync it. Will do so when I am back in the office. You can get Roland.h and .cpp from chrishamm's fork.

On 28 December 2015 16:16:57 GMT+00:00, Dan Newman <notifications@github.com> wrote:
>Looks like they haven't been sync'd up to the publicly visible github
>repo?  At least, I do not yet see those three files in the dev branch. 
>(Nor the master branch --  I know it's obsolete, but I checked there
>just in case.)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/dc42/RepRapFirmware/issues/23#issuecomment-167596916

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.
