### ISSUE TITLE
RepRapFirmware branch v2-dev corrupted.

### ISSUE THREAD

**Issue by leolongvu** [dc42/RepRapFirmware#230]
Hello

After a lots of tries I have been able to rebuild the most recent firmware as described in the BuildInstructions.md. I then tried to upload the firmware to the printer to check if it works before implementing my custom kinematics code. Unfortunately as the firmware updated the web interface shown the following notification:

"Could not establish a connection to the Duet firmware! Please check your settings and try again."

I then tried to connect the board to the PC via serial using Prontface and YAT. The connection is just frozen with Prontface, meanwhile I am able to connect to YAT but unable to get any feedback from the printer (e.g M115). I had to do a hard erase and reupload the precompiled firmware to get the connection back. 
I also tried to recompile the order version of the firmware but the mismatch branches of other projects just make it impossible to do so, I always get random errors. Is there a way to check which part of the firmware is corrupted?

**Comment by dc42** [comment]
AFAIK the current committed sources (v2-dev for RRF, main for everything else) work together; however I expect to commit changes to all 4 projects today, and this set definitely works.

**Comment by leolongvu** [comment]
It works after the update, thank you very much.
