### ISSUE TITLE
Where can i find codes for ESP-12 wifi model‘s firmware?

### ISSUE THREAD

**Issue by 0x3A2B** [dc42/RepRapFirmware#233]
I want know how ESP-12 communication with duet2 and add a wifi model on my 3D printer if i can.
It seems ESP-12 is a web server and use I2C to control duet2，am I right?

**Comment by dc42** [comment]
The communication between the ESP-12S and the Duet main processor is SPI. Early firmware versions ran the web server on the ESP. Later versions run the web server on the Duet main processor and the ESP just provides TCP/IP sockets. The ESP code is in projects CoreESP8266, DuetWiFiSocketServer and LwipESP8266.
