### ISSUE TITLE
Filament Load/Unload Modal Display Error

### ISSUE THREAD

**Issue by ctilley83** [dc42/RepRapFirmware#236]
I keep getting the following message and it seems to be an error related to displaying a modal inside of a web browser.  Tried in the latest Firefox and Safari as that's what I had to test with.

`
T0
M702
Error: M291: Attempt to create a message box that cannot be dismissed
`

System Information
Firmware: 2.02RC5(RTOS) (2018-11-28b1)
WiFi Server: 1.21
Web Interface: 1.22.5

**Comment by dc42** [comment]
https://github.com/dc42/RepRapFirmware/blob/dev/README.md
