### ISSUE TITLE
no connect-disconnect button after upgrading to 1.22.5

### ISSUE THREAD

**Issue by kostasbmwx3** [dc42/RepRapFirmware#238]
duet wifi
no connect-disconnect button after upgrading to 1.22.5 firmware web control

**Comment by T3P3** [comment]
That is expected, it autoconnects.

**Comment by kostasbmwx3** [comment]
i thought of that but no communication between machine and web control
  the strange thing is i dont see the buttons as the previous version in the top left corner...its gone

**Comment by dc42** [comment]
See "Support, issues and suggestions" in https://github.com/dc42/RepRapFirmware/blob/dev/README.md.
