### ISSUE TITLE
reprapFirmware  vs marlin 2.0. Clash of the Titans

### ISSUE THREAD

**Issue by ghost** [dc42/RepRapFirmware#242]
Marlin 2.0 and reprapFirmware.
Board used RURAMPS, Arduino DUE.
Is the firmware stable and productive for the Arduino DUE compared to the 32 bit reprapFirmware.
Interested in functionality and performance. And how will this affect print quality?

**Comment by dc42** [comment]
Hi Vladimir, are you the author of the RURAMPS fork of RRF?

The latest version of RRF is 2.02RC7 provisional, which I have just committed. It will be released later today subject to satisfactory testing. The most recent commits should only affect the web interface and CNC machines running RRF.

**Comment by badvision** [comment]
It's probably ok to close this for now since it's well-answered, no?

**Comment by dc42** [comment]
Yes.
