### ISSUE TITLE
Dual Z endstop, and Dual Z motor

### ISSUE THREAD

**Issue by vladimirRUS007** [dc42/RepRapFirmware#243]
Does the firmware support simultaneous use of the Dual Z endstop, Dual Z motor and Dual Y endstop, Dual Y motor.
Fee arduino DUE.
How to implement it.
It is also planned to do auto-calibration on an inductive sensor.
Will this all work in parallel.

**Comment by dc42** [comment]
Please do not ask for support by raising issues, use the forum at https://forum.duet3d.com instead.
