### ISSUE TITLE
Web interface - Endless loop in files and macros

### ISSUE THREAD

**Issue by kafledelius** [dc42/RepRapFirmware#244]
Hello.

After upgrading to the latest firmwares:

Firmware Version: | 1.20.1 (2018-01-08)
Web-Server: 1.20.1
Web interface: 1.22.6 (Tried downgrading)

I'm getting endless loops in the Macros and the Gcode files section.

Is this a known issue ?

**Comment by Jester3rdDimention** [comment]
Yeah, I am running into the issue. I have tried to remove the macros and the Gcode files and re update but it still is happening, if i go back to 1.20 then it stops happening but any version high i get this issue.

![fwv](https://user-images.githubusercontent.com/47227369/52084166-6ce42780-256f-11e9-8c66-4a0b66f21fb6.PNG)
![repeat](https://user-images.githubusercontent.com/47227369/52084167-6ce42780-256f-11e9-89d8-3e58c711c8a3.PNG)
![whats happening](https://user-images.githubusercontent.com/47227369/52084168-6ce42780-256f-11e9-8508-b718894e8d17.PNG)

**Comment by dc42** [comment]
This issue is caused by using incompatible versions of RepRapFirmware and DuetWebControl.
