### ISSUE TITLE
Issues with M106 and naming of Fan with C option

### ISSUE THREAD

**Issue by grbd** [dc42/RepRapFirmware#246]
Hi,
I recently updated the firmware from 2.01 to 2.02
on a Duet wifi 1.04 board

Firmware: 2.02(RTOS) (2018-12-24b1)
WiFi Server Version: 1.21
Web Interface Version: 1.22.6

I noticed that my hotend fan wasn't running
it turns out there may be a bug when using the C option to name a fan with the M106 command

It used to be like this in the config
```
M106 P0 S0 I0 F31 H-1 B1 CPartFan1                             ; Used to cool the part
M106 P2 S0 I0 F31 H1 L1 T60 CHotendFan1                          ; Used to cool the hotend
```

However I noticed when running this at the console I'd get spurious errors like this
`Error: M106: Logical pin H0 is not available to use for fan 2`
It was almost as if the name of the fan couldn't exceed 7 characters for fan 2, or 1 character for fan 0

Removing the Fan naming fixed the problem
```
M106 P0 S0 I0 F31 H-1 B1                             ; Used to cool the part
M106 P2 S0 I0 F31 H1 L1 T60                          ; Used to cool the hotend
```

**Comment by dc42** [comment]
Please see the readme file.
