### ISSUE TITLE
Panel due is locked with 1.09o

### ISSUE THREAD

**Issue by criticallimit** [dc42/RepRapFirmware#25]
My PanelDue is locked in the the new Version. Tapping on the screen is doing nothing. All Values are ok and are updatet, but if you klick on a button nothing happens. Like it´s locked.
Did a reset of the Panel and it was going to the print screen, but you cant click. Every time I do a reset it´s going back to the print screen updating all values correctly but the buttons are locked.

**Comment by thevisad** [comment]
I had a similar issue with my PanelDue after an update to 1.09n and flashing the PanelDue to the latest firmware. However, I could not proceed past the screen calibration. Did you also flash your PanelDue firmware as well?

**Comment by criticallimit** [comment]
Yes, Panel is up to date (1.13)

**Comment by thevisad** [comment]
What screen are you using and how are you powering the PanelDue?

**Comment by criticallimit** [comment]
standard screen 4.7" from www.think3dprint3d.com.
Powered from the Duet with standard cable.
Working without any issues before 1.09o

**Comment by dc42** [comment]
Please try reverting to 1.09m. There are some issues with code from another developer that I merged in and they could be causing these problems. 

On 28 December 2015 18:53:09 GMT+00:00, criticallimit <notifications@github.com> wrote:
>standard screen 4.7" from www.think3dprint3d.com.
>Powered from the Duet with standard cable.
>Working without any issues before 1.09o
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/dc42/RepRapFirmware/issues/25#issuecomment-167628238

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by BrianGilbert** [comment]
Assume this can be closed now that your up to r release?

**Comment by dc42** [comment]
Believed to be caused by buffer starvation occurring in the new output buffer code in 1.09o. Fixed in 1.09r.
