### ISSUE TITLE
dev branch doesn't build at the moment

### ISSUE THREAD

**Issue by gtjoseph** [dc42/RepRapFirmware#252]
Not sure if you knew...
make: *** No rule to make target 'src/Movement/Kinematics/CartesianKinematics.o', needed by 'Duet2CombinedFirmware.elf'.  Stop.

In the middle of something?

Which branch would you like me to do the M308 Generic Heater Control work in?

**Comment by dc42** [comment]
That file is no longer used. Your makefile is out of date, you need to force Eclipse to create a new one.
