### ISSUE TITLE
M408 with invalid S parameter clogs G-code buffer

### ISSUE THREAD

**Issue by tomasf** [dc42/RepRapFirmware#262]
Passing an (admittedly invalid) S value of 6 or greater (or a negative value) to `M408` causes things to behave strangely. Many G-code commands stop working.

`GCodes::GenerateJsonStatusResponse` doesn't handle these type cases, causing its `OutputBuffer` return value to be `nullptr`. This is interpreted by `GCodes::HandleMcode` to mean buffer runout, causing it to return `GCodeResult::notFinished` and the G-code buffer gets stuck in `GCodeBufferState::executing`.

`M122` backs this up: `http is doing "M408 S6" in state(s) 0`

**Comment by dc42** [comment]
Thanks, fixed in next 2.03 beta.

**Comment by dc42** [comment]
Now fixed.
