### ISSUE TITLE
1.24beta2+1: Hot end cooling fan full on after boot up

### ISSUE THREAD

**Issue by StephenRC** [dc42/RepRapFirmware#278]
Duet 085
Heater connected to Heater 2 (H1 connector broke off)
Thermister to H2 thermister connector

In config.g:
M106 P0 S0 H-1 C"Part Cooling"
M106 P1 T45 H2 C"Hotend Fan"
M563 P0 D0 H2 ; tool 0

1.23: hot end fan off until 45C is reached.
1.24beta2+1: Hot end cooling fan full on after boot up
1.24beta1: hot end fan off until 45C is reached.

**Comment by dc42** [comment]
Please upgrade to 1.25.
