### ISSUE TITLE
1.24beta2+1: Bed Heater not working

### ISSUE THREAD

**Issue by mike-o-tronic** [dc42/RepRapFirmware#282]
Updated my Duet 0.6 from 1.21RC5 to 1.24beta2+1 with the result the bed heater was not reacting anymore. Rolled back to 1.24beta1 and bed heater is working as usual.

Locking forward to see how the new firmware is doing :+1: 

Cheers
Mike

**Comment by mike-o-tronic** [comment]
A little update... The first rollback didn't quite work. 1.24beta1 (2019-02-16) started randomly turn atx power off before I even got ready to print. So I rolled back one more to 1.24beta1 (2019-02-03) and first print is successfully done, next is in progress.

**Comment by dc42** [comment]
This is not a support forum. https://forum.duet3d.com/
