### ISSUE TITLE
Use DHCP rather than static IP (192.168.1.10) as default in Network.h

### ISSUE THREAD

**Issue by dcnewman** [dc42/RepRapFirmware#29]
When the config.g cannot be accessed, the firmware still runs using compile-time defaults.  For the network, the default IP address is 192.168.1.10.  Might it make more sense to instead use 0.0.0.0 as the default IP address and thus kick the network stack into attempting to use DHCP to get a more-likely-to-be-useful IP address?

Impacted file would be Network.h

**Comment by dcnewman** [comment]
It would be better still, if the network code could attempt DHCP and, should that fail, then fall back to 192.168.1.10.

**Comment by dc42** [comment]
The default has been changed to use  DHCP.
