### ISSUE TITLE
Duet Maestro External Stepper E2 Dir pin not setup correctly

### ISSUE THREAD

**Issue by basriram** [dc42/RepRapFirmware#293]
The External Stepper (E2) uses an Analog pin for DIR and that causes the motor to spin in only one direction. Here is the configuration -
 { PIOA, PIO_PA18X1_AD1,		ID_PIOA, PIO_OUTPUT_0, PIO_DEFAULT,  **PIN_ATTR_ANALOG**,					**ADC1**,   NOT_ON_PWM,  NOT_ON_TIMER }, // E2 dir
Here is the same configuration for the second external stepper (E3) which works correctly -
  { PIOC, PIO_PC24,				ID_PIOC, PIO_OUTPUT_0, PIO_DEFAULT,  **PIN_ATTR_DIGITAL**,					**NO_ADC**, NOT_ON_PWM,  NOT_ON_TIMER }, // E3 dir

**Comment by dc42** [comment]
Those values in the table do not affect the ability of the firmware to use the pin for digital output. The PIB_ATTR_ANALOG and PIN_ATTR_DIGITAL values are not used anywhere, and the ADC1 value is only used if the firmware explicitly sets the pin to be an analog input. All 4 extruders connected to my Maestro are working normally.
