### ISSUE TITLE
Thermocouple issues

### ISSUE THREAD

**Issue by dang472** [dc42/RepRapFirmware#294]
Having issues with type K thermocouples. They were working fine until recently. Now everytime I power up my duet ethernet after a day of being powered off,  my thermocouples come up faulted.  My work around is to unplug the thermocouple  (i have them connected through connectors). Power up the duet and then plugin the thermocouple. I can then power on and off for a while without faults. 

Firmware 2.03RC2
config.g setting for thermocouple is M305 P2 X151 T"K" S"hotend1"

**Comment by dc42** [comment]
Please use the forum at https://forum.duet3d.com for support.
