### ISSUE TITLE
My BLTouch no longer works after upgrading to 2.03 (2019-06-13b2)

### ISSUE THREAD

**Issue by chichirod** [dc42/RepRapFirmware#296]

**Comment by chichirod** [comment]
I just upgraded to the latest firmware and now my BLtouch just flashes saying that it has already been activated before anything happens.

**Comment by giostark** [comment]
Hi chi,
Maybe is better use the forum ;-)
Did you come from an old firmware?
The BL it do at least one probe and then stop?
Look here : https://forum.duet3d.com/topic/10455/solved-bl-touch-deploy-only-one-time-with-2-03rc1/6
If you come from old firmware you probably have to rearrange the code in your bed.g
If is other stuff you have to wait expert suggestions.

**Comment by dc42** [comment]
BLTouch retested and working in release 2.04.
