### ISSUE TITLE
Add support for ZeroConf/Bonjour network discovery

### ISSUE THREAD

**Issue by TheBum** [dc42/RepRapFirmware#299]
It would be really handy to have this feature for Mac and Linux users so that we don’t have to deal with setting up a local DNS server or use hard-coded IP addresses.

**Comment by Renha** [comment]
isn't that already supported? I mean, my Ashwood machine is discoverable as ashwood.local.

**Comment by TheBum** [comment]
Maybe Ashwood is using custom firmware. I just know that I can’t get to my Crane using cranequad.local (the defined machine name). The web page for the OctoPi connected to my Snapmaker comes right up when I go to octopi.local.

**Comment by TheBum** [comment]
I just looked through the source code and it appears mDNS was disabled due to a buggy implementation. I have not discovered when it was disabled, but I suspect that your firmware version predates the change.

Maybe it's time to revisit it with a newer version of the support code?

**Comment by alexjx** [comment]
I could connect with the domain name without problem... what do you mean by "buggy implementation"?

**Comment by chrishamm** [comment]
It is already supported on the Duet WiFi because it could be easily enabled there, but an implementation for the Duet Ethernet/Maestro is not trivial and will require extra refactoring. It is planned, but there is no timeline for the implementation yet.

**Comment by chrishamm** [comment]
It's implemented in the latest v2 and v3 releases.
