### ISSUE TITLE
Invalid JSON (inf) from rr_status

### ISSUE THREAD

**Issue by tomasf** [dc42/RepRapFirmware#30]
rr_status intermittently reported `inf` for timesLeft.filament. This causes the web interface to fail to load.

    "timesLeft":{
        "file":0.0,
        "filament":inf,
        "layer":135.4
    }

This is very similar to the bug I reported in December here: http://forums.reprap.org/read.php?146,594372,594372#msg-594372

Firmware version: 1.09r-dc42 (2016-01-16)

Perhaps it's time to feed numbers through a function to make sure they're not infinite/NaN (and fall back to something parseable) before printing them as JSON :-)

**Comment by dc42** [comment]
Thanks for your report. The approach I use with code that I write is to
prove that division by zero cannot occur and NaNs cannot be generated.
However, the Print Monitor code was written by someone else. I will
review the code and rewrite it to avoid these issues.

David Crocker, Escher Technologies Ltd.
http://www.eschertech.com
Tel. +44 (0)20 8144 3265 or +44 (0)7977 211486
