### ISSUE TITLE
Updating radds from 1.21 to 2.04RC1 causes endstop issue

### ISSUE THREAD

**Issue by marlovdm** [dc42/RepRapFirmware#301]
Hello,
Today i attempted to update my delta printer with radds to version 2.04RC1.
Updating caused a issue with the endstops.
In particular, 
- When x,y and z endstops are connected, x is unresponsive.
- When two endstops are connected, the connected endstops work.
during my testing, my z-probe connected to z-min and worked fine.

This issue is very similar if not equal to the endstop issue i encountered when attempting to port rrf to smart ramps back in 2017.

**Comment by dc42** [comment]
Please retest with 2.04 release and submit a new issue for that version if it is still present.
