### ISSUE TITLE
Feature request: G-code preview

### ISSUE THREAD

**Issue by TheBum** [dc42/RepRapFirmware#304]
I'd like to see a G-code preview similar to the one in OctoPrint. It would help verify you have the G-code uploaded that you thought you did. My workaround now is to download the file from the Duet 2 (Maestro) and load it into Voxelizer, but downloads from the board are really slow.

**Comment by chrishamm** [comment]
This is not related to RepRapFirmware but to DuetWebControl. I suggest you open a new issue on my repository here: https://github.com/chrishamm/DuetWebControl/issues

**Comment by TheBum** [comment]
Sorry. I didn't think of those being separate applications.
