### ISSUE TITLE
config.g fails to save

### ISSUE THREAD

**Issue by sortinousn** [dc42/RepRapFirmware#308]
- Firmware: RepRapFirmware for Duet 2 WiFi/Ethernet 2.03RC5 (2019-06-05b5) 
- Duet WiFi Server Version: 1.23

When I make changes to config,g I get the error `Failed to upload config.g - network error`
Maybe out of the 5 times I make changes 3 of them fail because the config.g does not save. Once I restart the board I have to re-create the config.g file from config.g.bak.

I ran diagnostics (attached.).
[diagnostics.txt](https://github.com/dc42/RepRapFirmware/files/3532303/diagnostics.txt)

**Comment by dc42** [comment]
Please ugrade to firmware 2.04 stable and re-test.
