### ISSUE TITLE
Layer counter stops counting after layer 2

### ISSUE THREAD

**Issue by Spirre** [dc42/RepRapFirmware#31]
Seems like there is something wrong with the layer counter in the web GUI, it stops at 2 every time. Percentage works though.
Running 1.09r

**Comment by Spirre** [comment]
It seems like this problem only occur when you print with a raft. It only counts the layers for the raft, after that i stops.

**Comment by chrishamm** [comment]
I've fixed this in my fork and will provide a solution in my next release.

**Comment by dc42** [comment]
These changes from chrishamm were merged into my fork long ago, so I believe this issue is resolved.
