### ISSUE TITLE
Tool select (Tx) ignores pre/post scripts

### ISSUE THREAD

**Issue by orcinus** [dc42/RepRapFirmware#310]
After homing all axes from the web UI on a cold booted machine, subsequent tool changes from a gcode job started via PanelDue simply ignore all the pre/post scripts. Tools get selected, but the scripts don't get run.

If i home axes from PanelDue, however, jobs run from the GUI or the PanelDue will execute the tool change scripts just fine.

I have "Run free macro", "Run pre macro" and "Run post macro" turned on in the Web UI.

I'm not sure if this is a RRF bug, a PanelDue bug, or a web interface bug (or a combination of all three).

**Comment by orcinus** [comment]
It just occurred to me that maybe this happens when you hit print or select a tool too quickly after a fresh boot or a reboot. Does it take a while for RRF to load or cache the system gcode macros?

**Comment by chrishamm** [comment]
Tool change scripts are only processed after config.g has been fully read and if all axes are homed. Are you trying to change the tool in a homing macro?

**Comment by orcinus** [comment]
No, in a print job gcode file loaded and run immediately after homing.

**Comment by orcinus** [comment]
I'm not exactly sure what changed, but couldn't reproduce it anymore in the past 3 days.
I can close and reopen if it happens again?

**Comment by chrishamm** [comment]
I'll close it. If it happens again, either reopen this issue or create a new one.
