### ISSUE TITLE
WebControl 2.02 Extrusion Control dosn't work

### ISSUE THREAD

**Issue by stubbeDK** [dc42/RepRapFirmware#323]
![billede](https://user-images.githubusercontent.com/45252174/66593277-fafcbd00-eb96-11e9-8430-d6d81b44b013.png)

The buttons Extrude or Retract isn't enabled after heating up the hotend why? 
Have always worked. Can still do it from the console :)

**Comment by chrishamm** [comment]
I could reproduce this problem and I am working on a fix. In the future, please report DWC-related problems on the official DWC repo here: https://github.com/chrishamm/DuetWebControl/issues

**Comment by stubbeDK** [comment]
> 
> 
> I could reproduce this problem and I am working on a fix. In the future, please report DWC-related problems on the official DWC repo here: https://github.com/chrishamm/DuetWebControl/issues

Sorry about the miss placement, i know for next time and thanks :)
