### ISSUE TITLE
Missing mDNSResponder implementations in 2.04 dev branch?

### ISSUE THREAD

**Issue by alexjx** [dc42/RepRapFirmware#332]
Hi Dave,

I'm trying to rebuild my firmware from the latest 2.04 dev branch. But it complains missing mDNSResponse related references when linking. I found no such implementations in the codebase. 
Is it omitted intentional or accidental?
Thanks.
Jia

**Comment by dc42** [comment]
I have verified that the two MdsnResponder files are included in the repository. They are in src/networking/W5500Ethernet.
