### ISSUE TITLE
Feature Request: Matrix / Mesh Auto Bed Levelling

### ISSUE THREAD

**Issue by adamfilip** [dc42/RepRapFirmware#34]
Ability to measure multiple points on the bed to account for an unflat surface. similar to the mesh/matrix levelling features being developed for Marlin. this isnt the same as standard ABL where its just a plane. but its a mesh of points. 5x5 grid to detect peaks and valleys on the bed

**Comment by dc42** [comment]
This is implemented in firmware 1.17.
