### ISSUE TITLE
Feature Request: Add minimum PWM for FANs in M950

### ISSUE THREAD

**Issue by boa-pe** [dc42/RepRapFirmware#369]
It is useful to set minimum PWM for fans and scale 0-100% to minPWM-maxPWM instead of 0-maxPWM. This was setting low values for FAN like 5% will make fan to actualy spin.

**Comment by Billtopia** [comment]
Isn't that a thing already? When you set up the fan pin pwm use "L" and your minimum

**Comment by boa-pe** [comment]
Hmm.. I missed that. That is exactly what I had in mind.
