### ISSUE TITLE
M204 not supported, used by slic3r

### ISSUE THREAD

**Issue by dposea** [dc42/RepRapFirmware#37]
I tried to find info on this with google, I know it must have been addressed before, but I could not find anything.

**Comment by dcnewman** [comment]
IIRC, this M204 usage was added to slic3r in an attempt to make up for firmwares which lack any form of pressure advance (e.g., Marlin).  That in turn was motivated by experiments of some users suggesting that with their printer and firmware, adjusting the maximum accelerations on a per line segment basis provided some benefit.  However, for firmwares which do have functional pressure advance mechanisms (e.g., RepRapFirmware) you should simply disable slic3r's use of M204.

**Comment by nebbian** [comment]
Note, you can use a post processing script to turn M204's into M201's.  An example is here:
https://github.com/prusa3d/Slic3r/issues/106

**Comment by dc42** [comment]
M204 is on the list for supporting in a future release of RRF.

**Comment by dc42** [comment]
M204 is implemented in RRF 1.18.
