### ISSUE TITLE
M952 Not supported in RepRapFirmware 3.01-RC5

### ISSUE THREAD

**Issue by mattrsch** [dc42/RepRapFirmware#372]
When using RepRapFirmware 3.01-RC5,
executing a M952 command to re-address a tool board returns a warning.  Example:

M952 B121 A20
Warning: M952: Command is not supported

The command works properly in RepRapFirmware 3.01-RC4

**Comment by dc42** [comment]
Please try 3.01-RC7.

**Comment by mattrsch** [comment]
Thanks,  It is working in 3.01-RC7
