### ISSUE TITLE
Problem with Object Model RepRapFirmware 3.01-RC5

### ISSUE THREAD

**Issue by anraf1001** [dc42/RepRapFirmware#373]
After updating firmware to RRF3-RC5 any command in my scripts that were using object model like `if state.status == "Processing"` stopped working.
After sending M409 in my console it returns: `{"key":"","flags":"","result":{"boards":[{}],"directories":{},"fans":[{},{}],"heat":{},"inputs":[{},{},{},{},{},{},{},null,null,{},{}],"job":{},"limits":{},"move":{},"network":{},"scanner":{},"sensors":{},"seqs":{},"spindles":[{},{},{},{}],"state":{},"tools":[{}],"volumes":[{},{}]}}`

**Comment by dc42** [comment]
M409 with no key now returns just the root keys to avoid the response being too long to send. This is documented in the upgrade notes. Use M409 K"state" to see the complete state subtree of the OM.
