### ISSUE TITLE
Problem Updating to 301-RC5 with Duet2 WiFi

### ISSUE THREAD

**Issue by Jiter** [dc42/RepRapFirmware#374]
I try to update from -RC4 to -RC5.
Whenever I upload the Duet2CombinedFirmware.bin and Press "update"

Here is the Console Output:
2.4.2020, 11:22:27 | M997 S0Error: M997: In-application programming binary "Duet2CombinedIAP.bin" not found
2.4.2020, 11:22:24 | Upload of Duet2CombinedFirmware.bin successful after 1s
2.4.2020, 11:22:17 | Successfully deleted Duet2CombinedFirmware.bin

**Comment by chrishamm** [comment]
It's here: https://github.com/dc42/RepRapFirmware/releases/tag/3.0. Please use the forums for support next time.
