### ISSUE TITLE
Issue installing firmware version 3.01-RC11 - M997 S0

### ISSUE THREAD

**Issue by Imlbrown** [dc42/RepRapFirmware#393]
Hi DC42,

Great product and SW!  I just tried to install the latest firmware on my Duet2 WiFi board and after uploading the SW and clicking "yes" to the install I receive an error "M997 S0". The console log shows this "M997 S0
Error: M997: In-application programming binary "Duet2CombinedIAP.bin" not found".

I downloaded and attempted to install this file from the release page "Duet2CombinedFirmware.bin".

I am currently running 3.01-RC10.

Thanks!

**Comment by chrishamm** [comment]
That file is part of the RRF 3.0 release. Please use the forum for further support questions.

**Comment by Imlbrown** [comment]
Hi,

Sorry I am a bit confused, could you explain a bit more why you think this is a support question?  I tried to upgrade the firmware to the latest and the upgrade fails. This appears to be an issue with either the RC10 or RC11 release. I am not trying to use the M997 GCode command the update initiates the M997 command and it fails.

**Comment by Billtopia** [comment]
Reminders for those upgrading from version 2.x firmware: (1) you cannot upgrade to this release directly from 2.x, you must upgrade to the 3.0 release first; and (2) you will need to make substantial changes to your config.g file.
