### ISSUE TITLE
[Request] Velocity change smoothing configuration (ie. jerk parameter).

### ISSUE THREAD

**Issue by mirage335** [dc42/RepRapFirmware#41]
Some kind of "jerk" parameter, adjusting the smoothing between velocity changes, may improve print quality in some cases.

Theoretically, this might be implemented as a limit on the rate of change in acceleration (ie. jerk), just as acceleration is the rate of change in speed.

For TazMega, the threaded rod drive can couple extreme instantaneous force into the workpiece and toolheads. Even with 24 V-Slot wheels, this seems to cause the bed to bounce vertically when suddenly reversing direction. This may be contributing to front and back areas of printed parts showing gaps, as well as rough layers at heights above two centimeters.

Please consider adding some more tuning knobs to manage acceleration parameters.

**Comment by dc42** [comment]
This is already implemented, via M566.

**Comment by mirage335** [comment]
Awesome, much thanks!
