### ISSUE TITLE
M0 kills Telnet

### ISSUE THREAD

**Issue by tomasf** [dc42/RepRapFirmware#47]
When I use `M0` or `M1` from Telnet, nothing happens. The print continues, I get no reply, and Telnet functionality doesn't work until I reboot the Duet. Even new connections are non-responsive; the TCP connection opens, but no G-code commands work.

The behavior is similar to #42.

Firmware Version:   1.12a (2016-05-10)

**Comment by tomasf** [comment]
After some additional investigation, it turns out that this only happens if M0/M1 is run during a non-paused print. If there isn't a print running or if the current print is paused, it works as it should and Telnet continues to work.

**Comment by dc42** [comment]
Please try firmware 1.13 beta 1 and see if this still happens, also check it for issue #42 again.

**Comment by tomasf** [comment]
Oh, nice. It is indeed fixed in 1.13b1. #42 is also (still) fixed. Thanks!
