### ISSUE TITLE
Sending M112 (EStop) Through Serial While G28 (Homing) Running

### ISSUE THREAD

**Issue by avdoverflow** [dc42/RepRapFirmware#519]
Problem:  I am trying to control the Duet 2 Wifi using serial commands.  While the G28 Homing command is performed, sending a M112 command does not stop the homing.  

Test 1: I send G28 through YAT.  Then I send M112 while the system is homing.  The system completes the homing first and then performs an emergency stop.

Test 2: I send G91 G0 X50 through YAT.  Then I send M112 during movement.  M112 can halt a normal G91 G0 movement.

Test 3: I use the web interface to start a homing.  Pressing the web interface emergency stop button halts the homing mid-cycle.

Test 4: I configured M581 to create physical emergency stop.  Pressing this during homing stops the homing.

Note: This was reported in February 2021 by a separate user.
https://forum.duet3d.com/topic/21412/m112-and-g28-through-usb-and-fetching-current-position

Configuration:
Board - Duet 2 Wifi - W010165
Firmware - Duet Web Control 3.2.2

**Comment by T3P3** [comment]
Please test to see if this issue persists in 3.4.5, if it does then re-open the issue.

**Comment by dc42** [comment]
This is expected. GCode commands sent over a serial link are executed strictly sequentially. This is a limitation of serial interfaces.  Parsing GCode commands in the serial interface ISR would increase the interrupt latency too much. PanelDue sends the out-of-band sequence 0xF0 0x0F to cause an emergency stop that bypasses the command queue.
