### ISSUE TITLE
Software reset on Duet 2 Wifi running 3.3

### ISSUE THREAD

**Issue by natthapolvanasrivilai** [dc42/RepRapFirmware#528]
I've recently got a software reset from Duet 2 Wifi running 3.3
The reset is repeatable and is happened during the print.

M122
=== Diagnostics ===
RepRapFirmware for Duet 2 WiFi/Ethernet version 3.3 (2021-06-15 21:44:54) running on Duet WiFi 1.02 or later + DueX5
Board ID: 08DGM-956GU-DJ3SW-6JKD8-3SN6T-TUJRD
Used output buffers: 3 of 24 (24 max)
=== RTOS ===
Static ram: 23876
Dynamic ram: 77520 of which 0 recycled
Never used RAM 13020, free system stack 178 words
Tasks: NETWORK(ready,13.8%,235) HEAT(delaying,0.1%,330) Move(notifyWait,0.1%,340) DUEX(notifyWait,0.0%,24) MAIN(running,85.4%,441) IDLE(ready,0.7%,29), total 100.0%
Owned mutexes: WiFi(NETWORK)
=== Platform ===
Last reset 00:01:43 ago, cause: software
Last software reset at 2021-06-17 21:14, reason: AssertionFailed, none spinning, available RAM 9264, slot 2
Software reset code 0x4132 HFSR 0x00000000 CFSR 0x00000000 ICSR 0x0041f000 BFAR 0xe000ed38 SP 0x200031fc Task NETW Freestk 357 ok
Stack: 000001c6 00465e24 004065ff 004748d0 200079f0 20003270 00410d69 20003230 2001850d 00000026 00000002 4223f1a5 00000000 00000000 00000000 00000000 004748d0 200079f0 200094a4 200079f0 200034a8 00474888 20003270 2001850d 2001850d 004748d0 0041115d
**Error status: 0x04**
Aux0 errors 0,0,0
Step timer max interval 0
MCU temperature: min 40.2, current 40.6, max 41.2
Supply voltage: min 24.0, current 24.2, max 24.2, under voltage events: 0, over voltage events: 0, power good: yes
Heap OK, handles allocated/used 0/0, heap memory allocated/used/recyclable 0/0/0, gc cycles 0
Driver 0: position 0, standstill, SG min/max not available
Driver 1: position 0, standstill, SG min/max not available
Driver 2: position 0, standstill, SG min/max not available
Driver 3: position 0, standstill, SG min/max not available
Driver 4: position 0, standstill, SG min/max not available
Driver 5: position 0, standstill, SG min/max not available
Driver 6: position 0, standstill, SG min/max not available
Driver 7: position 0, standstill, SG min/max not available
Driver 8: position 0, standstill, SG min/max not available
Driver 9: position 0, standstill, SG min/max not available
Driver 10: position 0
Driver 11: position 0
Date/time: 2021-06-17 21:16:07
Cache data hit count 3738944411
Slowest loop: 6.83ms; fastest: 0.17ms
I2C nak errors 0, send timeouts 0, receive timeouts 0, finishTimeouts 0, resets 0
=== Storage ===
Free file entries: 10
SD card 0 detected, interface speed: 20.0MBytes/sec
SD card longest read time 3.5ms, write time 0.0ms, max retries 0
=== Move ===
DMs created 83, maxWait 0ms, bed compensation in use: none, comp offset 0.000
=== MainDDARing ===
Scheduled moves 0, completed moves 0, hiccups 0, stepErrors 0, LaErrors 0, Underruns [0, 0, 0], CDDA state -1
=== AuxDDARing ===
Scheduled moves 0, completed moves 0, hiccups 0, stepErrors 0, LaErrors 0, Underruns [0, 0, 0], CDDA state -1
=== Heat ===
Bed heaters = 0 -1 -1 -1, chamberHeaters = 2 -1 -1 -1
Heater 1 is on, I-accum = 0.0
=== GCodes ===
Segments left: 0
Movement lock held by null
HTTP is idle in state(s) 0
Telnet is idle in state(s) 0
File is idle in state(s) 0
USB is idle in state(s) 0
Aux is idle in state(s) 0
Trigger is idle in state(s) 0
Queue is idle in state(s) 0
LCD is idle in state(s) 0
Daemon is idle in state(s) 0
Autopause is idle in state(s) 0
Code queue is empty.
=== DueX ===
Read count 1, 0.58 reads/min
=== Network ===
Slowest loop: 39.75ms; fastest: 0.00ms
Responder states: HTTP(0) HTTP(0) HTTP(0) HTTP(0) FTP(0) Telnet(0), 0 sessions
HTTP sessions: 1 of 8
- WiFi -
Network state is active
WiFi module is connected to access point 
Failed messages: pending 0, notready 0, noresp 0
WiFi firmware version 1.26
WiFi MAC address 98:f4:ab:cf:c0:5d
WiFi Vcc 3.38, reset reason Power up
WiFi flash size 4194304, free heap 26072
WiFi IP address 192.168.1.37
WiFi signal strength -45dBm, mode 802.11n, reconnections 0, sleep mode modem
Clock register 00002002
Socket states: 0 0 0 0 0 0 0 0

According to the doc. the error 0x04 is due to output buffer starvation.

**Comment by dc42** [comment]
This type of issue should be reported on the forum, not here.
