### ISSUE TITLE
[FeatureRequest]: M98 repeat n amount of times

### ISSUE THREAD

**Issue by Th3M1k3y** [dc42/RepRapFirmware#536]
### Is your feature request related to a problem? Please describe.

Not a direct problem, but there isn't an elegant solution to run a task for a specific amount of times.

### Describe the solution you propose.

To do repeated prints with automatic part removal, it would be great to be able to give M98 a repeat parameter.

I am a machinist, and on our cnc machines we can give them an L parameter which specify how many times it should loop through the sub program.

To use this it would then be called like `M98 P"mymacro.g" L10` and it would then run mymacro.g 10 times.

If L isn't specified it would just run once, to keep it backwards compatible with already existing programs.

### Describe alternatives you've considered

The current workaround is to just make a file, and copy paste M98 to call the sub program the amount of times you need, it works, but isn't an elegant solution.

### Provide any additional context or information.

Ex. Photos, mockups, etc.

**Comment by T3P3** [comment]
You can use a while loop with iterations count to run M98 a set number of times:

https://duet3d.dozuki.com/Wiki/GCode_Meta_Commands#Section_Loop

**Comment by chrishamm** [comment]
I am closing this because it could be achieved using meta G-code commands.
