### ISSUE TITLE
[FeatureRequest]: M42 Pnn Pin state invert option

### ISSUE THREAD

**Issue by Jimmyboy83** [dc42/RepRapFirmware#540]
### Is your feature request related to a problem? Please describe.

Hi! When connecting relay to board, it will be very useful to invert state of pin  to opposite.
Ex. : Pin 5 state is high. Send command M42 P5 S999 and state of pin inverted to low or vise versa.

### Describe the solution you propose.

Add option to M42 command to invert state of pin
Ex. : M42 Pnn I or M42 Pnn S999

**Comment by dc42** [comment]
Inverting the pin is already possible by using ! in front of the pin name.
