### ISSUE TITLE
[FeatureRequest]: Input Popup Message Panel

### ISSUE THREAD

**Issue by Hernicz** [dc42/RepRapFirmware#546]
### Is your feature request related to a problem? Please describe.

It's not a problem.

### Describe the solution you propose.

It would be great if we could have popup input window where we can type numbers and text and use this data with GCode meta commands / store them as variables.

This input panel could have a timeout option, so if the operator doesn't type anything it wouldn't return anything and the Macro would use predefined default values.

**Comment by T3P3** [comment]
Implemented with M291 in RRF 3.5

https://docs.duet3d.com/en/User_manual/Reference/Gcodes#m291-display-message-and-optionally-wait-for-response

> - S5: (RRF 3.5 and later) Prompt for an integer value. L is the minimum accepted value (default 0), H is the maximum accepted value (default unlimited), and F is the default value. The integer is available to be used in the ["input" constant](https://docs.duet3d.com/User_manual/Reference/Gcode_meta_commands#named-constants)
> - S6: (RRF 3.5 and later) Prompt for a floating point value. L is the minimum accepted value (default 0.0), H is the maximum accepted value, and F is the default value. The floating point value is available to be used in the ["input" constant](https://docs.duet3d.com/User_manual/Reference/Gcode_meta_commands#named-constants)
> - S7: (RRF 3.5 and later) Prompt for a string value. L is the minimum number of characters (default 1), H is the maximum number of characters (default 10), and F is the default value. The string is available to be used in the ["input" constant](https://docs.duet3d.com/User_manual/Reference/Gcode_meta_commands#named-constants)
