### ISSUE TITLE
[FeatureRequest]: Add Single Block Mode in DWC

### ISSUE THREAD

**Issue by raffa1799** [dc42/RepRapFirmware#548]
### Is your feature request related to a problem? Please describe.

Ex. I'm always frustrated when...
i run custom gcode and i find and debug errors, in big gcode files  

### Describe the solution you propose.

Ex. It would be great if...
add to duet web control  the option songle block for find errors in gcode more fast and precise

### Describe alternatives you've considered

Ex. A workaround exists but it is tedius, for example...

### Provide any additional context or information.

Ex. Photos, mockups, etc.

**Comment by dc42** [comment]
Closing issue due to insufficient detail provided, and it appears to be related to DWC not RRF.
