### ISSUE TITLE
Triangle interpolation: point outside all triangles!

### ISSUE THREAD

**Issue by franklima260** [dc42/RepRapFirmware#55]
The sheer number of these messages renders the interface unusable. I understand the the error message is harmless but it is really bothersome.

![all points outside](https://cloud.githubusercontent.com/assets/4514540/17529182/ff62e652-5e37-11e6-829d-4c402bf59e73.png)

Is there any way to disable this error message?

**Comment by dc42** [comment]
You should only see this message during homing, if ever. Is that the case? If you are seeing it more often then there may be something wrong with your choice of probe points. The first four should be in an anticlockwise square at the corners of the bed starting near (0,0), and the last one in the centre.

You can set a timeout for messages to disappear on the |Settings page of the web interface.

**Comment by franklima260** [comment]
Here are my points:

M557 P0 X50 Y320                        ; first point
M557 P1 X320 Y320                    ; ...probe points...
M557 P2 X320 Y50                   ; ...for bed...
M557 P3 X185 Y185
M557 P4 X50 Y50                     ; ...levelling

Why would the order of the points affect the math?

The screen get covered in the error message more or less continuously during the print.
The problem with making the notification timeout slower is that most notifications are useful and I don't want to miss them.

![image](https://cloud.githubusercontent.com/assets/4514540/17582143/9e1b4c02-5f6f-11e6-8725-9d3f5a380f7b.png)

**Comment by dc42** [comment]
So your points are NOT in the required order (see my previous reply), which explains the problem.

I'll add a firmware wishlist to reject points that are in the wrong order, or to re-order them so that they are.
