### ISSUE TITLE
[FeatureRequest]: accelerometer/imu  crash detector 

### ISSUE THREAD

**Issue by herrtschaefer** [dc42/RepRapFirmware#567]
### Is your feature request related to a problem? Please describe.

It is not strictly tied to an issue, but I have had some failed prints where the print head got stuck on a rough Layer and caused layer shifts etc. and on tool changes it then crashed into the tool posts.

### Describe the solution you propose.

An accelerometer in the tool or on tool changers on the carriage. During calibration the motion system is characterized and during moves the firmware checks accelerometer data and compares it against expectations. Also deviations from commanded acceleration eg. Z axis acceleration on xy move (on corexy) can indicate z crash or bumpy surface. It then could trigger a macro for the user to handle the case giving data about the crash as param.

### Describe alternatives you've considered

A dedicated microcontroller board that triggers a gpio  pin used as trigger on duet board.
No information about expected movement could lead to false triggers.
Maybe an (official) duet board that has a dedicated microcontroller to offload processing off the motion hardware but with a protocol that feeds the crash detector with expected motion and physics parameters off the printer. Maybe complemented with piezo or strain gauges.

### Provide any additional context or information.

Ex. Photos, mockups, etc.

**Comment by T3P3** [comment]
believed superseded by this: https://github.com/Duet3D/RepRapFirmware/issues/829
