### ISSUE TITLE
Resume print after M600 from within a macro

### ISSUE THREAD

**Issue by wschadow** [dc42/RepRapFirmware#572]
### Is your feature request related to a problem? Please describe.

It seems that it's not possible to resume a print from a macros when a M600 is issued. A macro like below does not work. It requires extra klicks to go to the status menu and press the resume button

; ================================================================================
; called when M600 is issued.
; ================================================================================
;
; M98 P"0:macros/01-Filament_Handling/03-Change_Filament"   ; call macro to change filament
;
M291 P"Press OK to resume print." S2                         ; display message
M24                                                                              ;  resume print
;
; ==============================================================================
;

### Describe the solution you propose.

Ex. It would be great if...

### Describe alternatives you've considered

Ex. A workaround exists but it is tedius, for example...

### Provide any additional context or information.

Ex. Photos, mockups, etc.

**Comment by x0rtrunks** [comment]
Dealt with in forum thread. M600 cannot be used from a macro, only from a print file and M24 is not required.
