### ISSUE TITLE
3.4.5 homing speed drastically slowed

### ISSUE THREAD

**Issue by NNygren** [dc42/RepRapFirmware#595]
Using Duet 3 mini 5+ board on cartesian style printer

Issue after upgrading to 3.4.5 during the homing sequences occurred on the axis being told to travel back a few mm.  The movement would happen normally during the H1 home, but move at a snails pace during the H2 portion.

On X and Y:
G1 H1 X-265 F3600 ; move quickly to X axis end <-- MOVES NORMALLY
G1 H2 X10 F6000    ; go back a few mm  <-- HERE IS WHERE THE AXIS MOVES AT A SNAILS PACE.

On Z homing:
G30 ;  <-- LOWERS Z AT NORMAL SPEED FIRST TIME, BUT SUBSEQUENT RAISES AND LOWERS ARE SO SLOW I COULD BARELY TELL THE GANTRY WAS MOVING.  RESULTS IN FAILED Z PROBE.

Downgraded to 3.4.4 which works a treat.  Just thought I'd let you know in case this is the first you've seen the issue.
config.g file attached for reference in case you need it.

[config (2).zip](https://github.com/Duet3D/RepRapFirmware/files/10233052/config.2.zip)

**Comment by dc42** [comment]
FYI I already started looking at this after seeing your forum report, and resolving this is one of my top priorities once we have completed the release of RRF 3.5beta1.
