### ISSUE TITLE
Speed up motion generation floating point calculations on SAMC21

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#616]
Applies to the 1XD/1LC,

Need to speed up step ISR:
(a) can we use a separate interrupt for the step interrupt instead of the general timer mechanism,
(b) consider using a faster floating point maths library,
(c) put some of the code in RAM if we have space (tool board reports 4360 bytes never used but that will drop if we configure more sensors)

**Comment by dc42** [comment]
Replaced fadd, fsub, fmul and fdiv functions by Qfplib-M0-full functions in SAMC21 configurations

**Comment by dc42** [comment]
Test results: using 400 steps/mm, ZVDD shaping@40Hz, single 200mm movement, 1000 mm/sec^2 acceleration:
- 3.5.0-beta.4 get 56 to 58 hiccups @ F15000 = 100kHz step rate
- With Qfplib: get 53 to 59 hiccups @ F16150 = 107.7kHz step rate

**Comment by dc42** [comment]
Prints using a tool board are satisfactory.
