### ISSUE TITLE
M950 R (spindle) configuration to allow min/max PWM to be specified

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#618]
Requested
"The issue I think is the hobby ESC takes a PWM signal where a 1ms pulse width is 0 rpm and a 2ms pulse width is max rpm. Anything outside these pulse width is treated as an error and the ESC will wait until the signal returns to 1ms before spinning the motor again.

If the M950 command also took a parameter for the duty cycle that relates to the min & max rpm then this would allow better control over this type of spindle. So the M950 command may look like this:

M950 R0 C"!exp.heater3" L12000 Q50 B5:10

to create a spindle that has a max speed of 12000 rpm which is achieved with a pwm signal of 50Hz @ 10% duty cycle, and 0 rpm is achieved with a signal of 50Hz @ 5% duty cycle.

The B parameter would default to 0:100 to mimic the current implementation if not set by the user"

**Comment by T3P3** [comment]
planned for RRF 3.5:
https://docs.duet3d.com/en/User_manual/Reference/Gcodes#m950-create-heater-fan-spindle-or-gpioservo-pin
> Kaaa(:bbb[:ccc]) (optional, for spindles only, RRF 3.5 and later) PWM values (0..1) for spindle control (max [aaa] - or - min, max [aaa:bbb] - or - min, max, idle [aaa:bbb:ccc])

**Comment by chrishamm** [comment]
AFAICS this is the same use-case for which I implemented the optional idle PWM parameter of M950 (see `ccc` parameter in the quote above). This has been implemented since RepRapFirmware 3.4.1rc2.
