### ISSUE TITLE
Allow a fixed offset to be applied to a temperature sensor.

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#624]
While PT100s are quite accurate, thermistors etc have a range of accuracies. If profiles are to be shared between printers then some users may want to calibrate and offset the temperatures between different machines. 

Initially a simple linear adjustment would probably be sufficient as users could use the filament handling system to have different adjustments at different temperatures.

https://forum.duet3d.com/topic/9048/thermocouple-temperature-offset/8

https://forum.duet3d.com/topic/27202/normalizing-temperature-sensors-across-machines/4

**Comment by dc42** [comment]
Implemented in 3.5.
