### ISSUE TITLE
G29 Checksum Error (1.17 Dev6)

### ISSUE THREAD

**Issue by Sniffle** [dc42/RepRapFirmware#68]
Not sure how you would like testers to report potential problems from the testing of the Dev firmware.  At least this initial time I will post both here and on duet3d forums to find out where you would prefer reports be placed.

Machine: C-bot Variant CoreXY
Board: Duetwifi 1.0
Additions: 7" Paneldue, IRProbe
Firmware Version: 1.17 Dev6

Description of probelm and steps taken to produce:
Following Gcodes entered manually.
M557 X30:290 Y70:290 S40
G28
G29

Response from system after G29 finishes:
Height map saved to file heightmap.csv - 42 points probed, mean error 0.11, deviation 0.24
Checksum error on line 203652

Additional notes:
I did this 2 other times while adjusting the grid boundaries to make it probe the area of the bed i wanted.
the following checksum errors also occured
Checksum error on line 202354
Checksum Error on line 202718

**Comment by dc42** [comment]
I'm sorry for the late response. Checksum errors normally indicate that the UART or its associated buffer experienced a receive overrun. It is to guard against overrun that we use checksums on the commands sent by PanelDue. As most commands sent by PanelDue are status requests which get repeated, they are harmless. Checksum errors should be very rare in the most recent firmware builds.
