### ISSUE TITLE
unable to download these in RAW mode, can you provide a ZIP?

### ISSUE THREAD

**Issue by gzcwnk** [dc42/RepRapFirmware#69]
Or a method that works via windows, thanks

**Comment by Alex9779** [comment]
I click on the binaries and then on "Download" on the upper right with right mouse button and select "Save link as...".
Works for me on every OS and browser...

Although I don't like binaries and source in one repo either.
@dc42 ever considered using the release feature of Github?

**Comment by dc42** [comment]
I will add a ZIP when I next update the device driver, or sooner.

**Comment by dc42** [comment]
I now provide a zip file.
