### ISSUE TITLE
M291 S2 not unblocking/Unblocking after timeout.

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#738]
As reported in forum thread https://forum.duet3d.com/topic/30877/3-5beta1-movement-issue-on-cnc-6xd-some-minors

M291 S2 in a program does not continue by M292 P0/M292/pressing OK. After the window closed it still in processing state with no window/reaction to M292. M292 P0/M292/pressing OK works fine with M291 S3.

May be fixed in 3.5b3

**Comment by T3P3** [comment]
Also related to:

https://forum.duet3d.com/topic/32054/m291-some-behavior-not-matching-documentation

>Issue #1 - The gcode dictionary for M291 with S=2 (as on line 4) says is the T parameter will be ignored (because S=2 is blocking). In practice, after 10 seconds, execution is unblocked. I am using this as a "feature" to make my macro work, but it seems wrong.

**Comment by T3P3** [comment]
Need to consider if this is a bug or an undocumented feature, suggestion from forum thread:

> For modes that are blocking and can have only one response (S=2):
> 
> - The display is instructed to show the message for the duration specified with the T parameter, if one is provided and <=0.
> 
> - If T >0, RRF will wait for an m292 response from the display for the specified duration, then assume an "OK" response from the display and resume gcode execution. _This is the current, incorrect behavior._
> 
> - If RRF has a subsequent message to display, it will not send a message to the display instructing it to terminate the existing message until the time period T expires. This is needed to preserve the blocking nature of the mode.

**Comment by AndyEveritt** [comment]
Could not replicate on Duet 3 SBC - 3.4.1. Will try 3.5-b1 & 3.5-b3

**Comment by AndyEveritt** [comment]
Using Duet3 Mini 5+ with 3.5.0-b1 the following behaviour exists:
- `M291 S2 P"xxx"` blocks and pressing ok clears message succesfully
- `M291 S2 P"xxx" T3` message incorrectly times out after 3 seconds
  - Same occurs with `S3`
- Could not get into the state where Duet is still in `processing` state

Same behaviour using 3.5.0-b3

There appear to be 2 potentially separate issues:
1. The `T` parameter is **not** being ignored when using `S2/S3`
    - Reproduced in 3.5.0-b1&3 in standalone mode
    - Not present in 3.4.5 (SBC & standalone)
2. `M292` does not clear a `M291 S2` message
    - Not reproducable in standalone mode on 3.4.5 & 3.5.0-b1&3
    - Not present in 3.4.5 with SBC
    - To be tested with 3.5.0-bX with SBC

**Comment by AndyEveritt** [comment]
3.5.0-b1 behaviour:
- `M291 R"test" P"Press OK to begin" S2`
  - SBC: Pressing `ok` or clearing the message with `M292` causes the duet to hang
  - Standalone: Pressing `ok` or clearing the message with `M292` behaves normally
- `M291 R"test" P"Press OK to begin" S3`
  - SBC: Behaves normally
  - Standalone: Behaves normally
- `M291 R"test" P"Press OK to begin" S2 T3`
  - SBC: Message incorrectly times out after 3 seconds
  - Standalone: Message incorrectly times out after 3 seconds

**Comment by AndyEveritt** [comment]
3.5.0-b3 behaviour:
- `M291 R"test" P"Press OK to begin" S2`
  - SBC: Pressing `ok` or clearing the message with `M292` causes the duet to hang
  - Standalone: Pressing `ok` or clearing the message with `M292` behaves normally
- `M291 R"test" P"Press OK to begin" S3`
  - SBC: Behaves normally
  - Standalone: Behaves normally
- `M291 R"test" P"Press OK to begin" S2 T3`
  - SBC: Message incorrectly times out after 3 seconds
  - SBC: If you press `ok` before timeout, Duet hangs until timeout is finished
  - Standalone: Message incorrectly times out after 3 seconds
  - Standalone: If you press `ok` before timeout, Duet does not hang

**Comment by dc42** [comment]
Changed RRF and updated the documentation so that the timeout is forced to zero unless the mode is 0 or 1 or a Cancel button is displayed (i.e. mode 3, or mode >= 4 with the J1 parameter used to provide a Cancel button).

**Comment by chrishamm** [comment]
I cannot reproduce any hangs in SBC mode with the latest state from GitHub. The code in RRF for handling timeouts looks fine to me, too.

**Comment by AndyEveritt** [comment]
3.5.0-b4 behaviour:

- `M291 R"test" P"Press OK to begin" S2`
  - SBC: Pressing ok or clearing the message with M292 behaves normally
  - Standalone: Pressing ok or clearing the message with M292 behaves normally
- `M291 R"test" P"Press OK to begin" S3`
  - SBC: Behaves normally
  - Standalone: Behaves normally
- `M291 R"test" P"Press OK to begin" S2 T3`
  - SBC: Message does not timeout & Duet does not hang after clearing message
  - Standalone: Message does not timeout & Duet does not hang after clearing message
