### ISSUE TITLE
Input shaping with short moves

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#747]
Input shaping not working at all on accelerate/decelerate moves . Proposed fix is as described in the "limiting speed and acceleration on small moves" feature request

Also is an issue when mesh bed compensation is enabled:

When mesh bed comp enabled, the segmentation for bed comp gives rise to acceleration and deceleration segments that are a little longer (35mm) than the acceleration and deceleration lengths before IS  applied (28.36mm). So there is presumably insufficient steady segment (6.64mm) to apply IS to the acceleration and deceleration. 

A work around would be to have an option to disable mesh bed comp for travel moves. This is only safe if Z lift is used.

https://forum.duet3d.com/topic/29551/input-shaping-cant-work-with-short-move

**Comment by dc42** [comment]
Fixed in 3.6.
