### ISSUE TITLE
M226 Pause

### ISSUE THREAD

**Issue by totalretribution** [dc42/RepRapFirmware#75]
Hi,
I'm trying to use M226 in a GCode file and it does not seem to work. The printer stops however on both the LCD and web interface it has the status "Pausing" and no matter what I try to do the duet does not respond.

I added an M70 message in the Pause.g code to see if that even is called and it seems the duet does not get that far.

Thanks
TotalRetribution

**Comment by dc42** [comment]
This is a known issue in firmware 1.17 and 1.17a. It is fixed in 1.17b.

**Comment by totalretribution** [comment]
Sorry, I thought I was on 1.17b. I will update now.
