### ISSUE TITLE
Can't pause while bed or tool is heating

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#763]
Need to flag the M109/190/116 command as restartable.

Also see the bug about pausing because of a heater fault during M190.

Potential related to "Allow cancellation of M116 waits and macros"

**Comment by chrishamm** [comment]
Fixed by b57696e70c63945ef5215e12f424cc96bcec0672. M116 as part of tpostN.g cannot be interrupted unless it is flagged restartable via M98 R1 (yet to be tested).

**Comment by T3P3** [comment]
as of

`FIRMWARE_NAME: RepRapFirmware for Duet 3 Mini 5+ FIRMWARE_VERSION: 3.5.0-beta.4+ ELECTRONICS: Duet 3 Mini5plus Ethernet FIRMWARE_DATE: 2023-08-15 14:01:22`

The following at the start of a print file **do** allow a pause to occur while waiting:
M104, M140, G10, M568 setting a temperature, followed by M116
M109 and M190 setting a temperature and waiting.
