### ISSUE TITLE
Support filament runout sensors (not filament monitors) over CAN-FD bus

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#766]
Support three configurations:
1) Extruder on CAN-FD expansion, filament sensor on mainboard
2) Extruder on mainboard, filament sensor on CAN-FD expansion
3) Extruder on CAN-FD expansion, filament sensor on different CAN-FD expansion board.

https://forum.duet3d.com/post/243076

**Comment by dc42** [comment]
Implemented in 3.5-dev but not yet tested.
