### ISSUE TITLE
Heater fan doesn't turn off

### ISSUE THREAD

**Issue by phcella** [dc42/RepRapFirmware#77]
Hi David,

I was using the 1.14c and the heater fan only turns on while the temp is higher than 100ºC (i guess). But now on 1.17c, the fan is always on.

Please let me know when this problem is fixed.

Thanks 
Pedro

**Comment by dc42** [comment]
Please use the forums for general support questions like this, either https://www.duet3d.com/forum/index.php or http://forums.reprap.org/list.php?416. Only confirmed firmware issues should be logged here.
