### ISSUE TITLE
Reduce EXP1HCL & M23CL closed loop motor noise

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#776]
Compare noise level with another closed loop driver as a baseline

Compare noise level with the magnetic encoder rather than quadrature.

Do we need a separate velocity loop? Do we need velocity feedforward, if so then how should we tune it? (velocity feed forward added as an experimental feature in 3.5b3)

What about acceleration feedforward? Do we need to tune PID using a ramp instead of a step so that the velocity is finite?

**Comment by dc42** [comment]
Completed in Duet3Expansion 3.5-dev.
