### ISSUE TITLE
EXP1HCL: option to generate position error events in open loop mode

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#778]
https://forum.duet3d.com/topic/30953/accurate-stall-detection-using-the-1hcl

**Comment by T3P3** [comment]
This is for the M23CL and the 1HCL, priority for 3.5.0

**Comment by dc42** [comment]
Met the original requirement by adding a new "assisted open loop" mode, which works like open loop mode but uses the MCU to advance the phase as required, and increases motor current with increasing measured error.
