### ISSUE TITLE
Neopixel support on TOOL1LC

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#782]
More generally, support Neopixels on any output port, including on expansion boards. Use SPI+DMA if available, else bit banging. 

STM port already has this but using a slightly different scheme

https://forum.duet3d.com/topic/26170/neopixel-support-on-1lc

https://forum.duet3d.com/topic/32125/connection-between-two-duet3-mini-via-can

**Comment by dc42** [comment]
Implemented in firmware 3.5. Note, only the IO0_OUT is is available to drive Neopixel LEDs and the current available from +5V is low, so only a few LEDs can be driven.
