### ISSUE TITLE
Bug uploading large files since 3.4.2

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#795]
Uploading gcode files greater than ~16mb on Duet 3 mini 5+ Ethernet in RRF versions later than 3.4.2 can fail in some network configurations.

Initial issue found on 6HC over Ethernet

Uploading a ".dummy" file works

M39 reports: 
SD card in slot 0: capacity 15.93GB, partition size 15.93GB, free space 15.73GB, speed 25.00MBytes/sec, cluster size 64kB

using M122 P104 S400 to write a 400Mb dummy file to SD card works.

Succeeds with Wireshark capturing enabled.

**Comment by dc42** [comment]
Forum thread https://forum.duet3d.com/topic/32542/gcode-upload-issue-after-upgrade could be related.
