### ISSUE TITLE
Heater fault pause resumes after the M109/M116/M190 command

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#798]
https://forum.duet3d.com/topic/28583/bug-in-resume-logic-after-a-heater-fault/3

**Comment by T3P3** [comment]
needs to be able to resume on the command that was not finished. Related to:
https://github.com/Duet3D/RepRapFirmware/issues/763

**Comment by chrishamm** [comment]
M109/M116/M190 now waits on the file channels if a queried heater is in "fault" state. Since we can now pause/cancel those codes if necessary, RRF restarts them on pause/resume.
