### ISSUE TITLE
Extra M669 parameters are not ignored

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#801]
https://forum.duet3d.com/post/277939

; Axes configuration executed by config.g
M584 X0.0 Y0.1:0.3 Z0.2:0.4
M669 K0 X1:0:0:0 Y0:1:0:1 Z0:0:1:0

In this example there are 3 motors but the M669 command has 4 entries per axis. In consequence, the forward matrix is computed incorrectly and some axes don't move properly.

Correcting it to the following solved the problem:

M669 K0 X1:0:0 Y0:1:0 Z0:0:1

**Comment by dc42** [comment]
Changed for 3.5.0-beta.4 so that an error will be reported if the number of coefficients per axis exceed the total number of axes.
