### ISSUE TITLE
[Bug]3.5b2 12864 object-model value items are null

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#806]
### Duet Forum Discussion Thread

https://forum.duet3d.com/topic/31899/3-5b2-12864-object-model-value-items-are-null

### Which Duet products are you using?

- [ ] Duet2-Wifi
- [ ] Duet2-Ethernet
- [ ] Duet Expansion Breakout Board
- [ ] Duex2
- [ ] Duex5
- [ ] Duet2-Maestro
- [ ] Maestro Dual Driver Expansion
- [ ] Duet3-6HC
- [ ] Duet3-3HC
- [ ] Duet3-1XD
- [ ] Duet3-1LC
- [ ] Duet3-Tool Distribution Board
- [ ] Duet3-Mini5+
- [ ] Duet3-Mini2+
- [ ] Raspberry Pi or other SBC
- [ ] SmartEffector
- [ ] Magnetic Filament Sensor
- [ ] Laser Filament Sensor
- [ ] PT100 Daughterboard
- [ ] Thermocouple Daughterboard
- [ ] PanelDue
- [ ] Other
- [ ] None

### Firmware Version

3.5.b2

### Duet Web Control Version

N/a

### Are you using a Single Board Computer (RaspberryPi) with your Duet?

- [ ] Yes I use a SBC.
- [X] No I do not use a SBC.

### Please upload the results of sending M122 in the gcode console.

```shell
M122 Report
```

### Please upload the content of your config.g file.

```gcode
Config.g
```

### Please upload the content of any other releveant macro files.

```gcode
value C80 N{state.status} W20 H2
```

### What happened?

I've tried doing something simple like:
value C80 N{state.status} W20 H2 as a test, and the string rendered is null.

**Comment by dc42** [comment]
Fixed in source code for 3.5.0-beta.4
