### ISSUE TITLE
file not found "MessageFormats.h" due to WiFi/Wifi spelling .cproject

### ISSUE THREAD

**Issue by tobbelobb** [dc42/RepRapFirmware#812]
I got a file not found "MessageFormats.h" error when trying to build today.

Turned out the DuetWifiSocketServer was spelled with a capital F (WiFi) in the .cproject file. Changing it to lowercase f (Wifi) fixed the issue for me.

https://github.com/Duet3D/RepRapFirmware/blob/0055cbdf32983bad645181ab03889740ee0edd97/.cproject#L612

The DuetWifiSocketServer repo itself uses lowercase, so we should make the two match.

**Comment by dc42** [comment]
The repository name is DuetWiFiSocketServer (with uppercase F), so that should be the name of the folder containing that project in your Eclipse workspace, as it is mine. I suspect that you created the folder with the wrong name.

**Comment by tobbelobb** [comment]
You're right. This taught me something about Github. In my bash history:
```
$ git clone git@github.com:Duet3d/DuetWifiSocketServer.git
```
In the repo itself:
```
$ git remote -v
origin	git@github.com:Duet3d/DuetWifiSocketServer.git (fetch)
origin	git@github.com:Duet3d/DuetWifiSocketServer.git (push)
```

... both lowercase f. But going to the website, one can see that Github silently fixes my typo and prints the fixed version back in the tab title. 
![Screenshot from 2023-04-30 11-17-55](https://user-images.githubusercontent.com/5753253/235345501-09e10b2c-728e-432c-bde4-903b6d636cee.png)

So it silently does the same fix to my git requests from the command line, and there's no warning or anything.
