### ISSUE TITLE
[FeatureRequest]: monitoring of closed loop motors

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#817]
### Is your feature request related to a problem? Please describe.

Allow monitoring of closed loop motors attached to the 1HCL and M23CL.

If the information was available in the Object Model then plugins and DWC could use it.

### Describe the solution you propose.

Report the closed loop current error, phase shift and potentially coil A and B current in the OM for each closed loop motor. probably at a similar frequency to temperature and other continuously updated data.

### Describe alternatives you've considered

A third party current monitor could potentially be used on the 1HCL, on the Motor23CL this would not be easy to use.

**Comment by dc42** [comment]
I don't see how this would be useful as the request now stands, because these quantities vary very rapidly, so taking a snapshot every 250ms wouldn't give a true indication of what is happening.

**Comment by T3P3** [comment]
potentially a running mean, and a peak reported every 250ms could be useful?

**Comment by T3P3** [comment]
implemented in 3.5
