### ISSUE TITLE
[FeatureRequest]: extend pow() to return an int instead of a float if appropriate.

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#826]
### Is your feature request related to a problem? Please describe.

Current implementation:
-- | -- | --
pow | (float, float)->float or (int, int)->int | Returns the first operand to the power of the second operand (supported in RRF 3.5beta3 and later). 
-- | -- | --

### Describe the solution you propose.

Return a result type of int if the operatnds are int, the second operand is non-negative, and the result fits in an int.

**Comment by dc42** [comment]
Implemented in 3.5.0-beta.4
