### ISSUE TITLE
[FeatureRequest]: Ceiling function

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#827]
### Is your feature request related to a problem? Please describe.

currently floor() is implemented but not ceil(),

### Describe the solution you propose.

<html>
<body>

ceil | float->int or float->float | Result is int if it fits in a 32-bit signed integer, else float.
-- | -- | --

</body>
</html>

**Comment by dc42** [comment]
Implemented in 3.4.0-beta.4
