### ISSUE TITLE
Can't enable WiFi in config.g on MB6HC 1.02 with WiFi module

### ISSUE THREAD

**Issue by dc42** [dc42/RepRapFirmware#840]
Running RRF 3.5.0-beta.3+ on MB6HC 1.02 with WiFi module, standalone mode. The following line in config.g doesn't enable the WiFi interface:

M552 I1 S1                          ; enable WiFi (doesn't seem to work)

Sending M552 I1 S1 via USB from YAT does enable the WiFi interface, although one "Authentication failed" response is returned (known issue with version 2.1 WiFi server).

**Comment by dc42** [comment]
Fixed in 3.5.0-beta.4 source code and back-ported to 3.4-dev

**Comment by Lino77** [comment]
The problem now exists again in 3.5.0-rc.1 via usb it start after sending M587 or M552 I1 S1

**Comment by dc42** [comment]
@Lino77 please try installing wifi firmware 2.1beta 6 from https://github.com/Duet3D/WiFiSocketServerRTOS/releases/tag/2.1beta6 and main firmware 3.5.0-rc.1++ from https://www.dropbox.com/scl/fo/gaxzegafmnmagaefo9mgc/h?rlkey=hk4wpttdje76oews8zkuh86q3&dl=0.

**Comment by Lino77** [comment]
Thanks, it now works, after renaming it to DuetWiFiModule_32S3.bin I was able to flash it, DuetWiFiServer_32S3.bin is probably incorrectly labeled on the github page. The upload via DWS renames the file DuetWiFiModule_32S3.bin to DuetWiFiServer.bin.

**Comment by Lino77** [comment]
Is it normal that the wifi module starts almost 2 minutes later

2023-12-13 22:11:52 [warn] Date and time set at power up + 00:00:04
2023-12-13 22:11:52 [warn] HTTP client 192.168.178.40 login succeeded (session key 0)
2023-12-13 22:13:20 [warn] WiFi module started
2023-12-13 22:13:20 [warn] WiFi module started
2023-12-13 22:13:27 [warn] WiFi module is connected to access point lunipu24, IP address 192.168.178.86

**Comment by Lino77** [comment]
The problem now exists again in 3.5.0-rc.3  wifi firmware 2.1beta 7 ,
via usb it start after sending M587 

M587
Remembered networks: none
ok
WiFi module started
ESP reported status change
ESP reported status change
WiFi: ./src/SocketServer.cpp(587): found network 'lunipu24' on channel=1, rssi=-45 mac=c8:0e:14:ad:20:fe
WiFi: ./src/SocketServer.cpp(587): found network 'WLAN-224934' on channel=1, rssi=-85 mac=4c:09:d4:1b:94:47
WiFi: ./src/SocketServer.cpp(587): found network 'WLAN-224934' on channel=1, rssi=-87 mac=7c:ff:4d:97:af:8c
WiFi: ./src/SocketServer.cpp(609): strongest known network 'lunipu24' on channel=1, rssi=-45 mac=c8:0e:14:ad:20:fe
WiFi module is connected to access point lunipu24, IP address 192.168.178.86
M587
Remembered networks:
lunipu24 IP=0.0.0.0 GW=0.0.0.0 NM=0.0.0.0
ok

**Comment by dc42** [comment]
> Is it normal that the wifi module starts almost 2 minutes later
> 
> 2023-12-13 22:11:52 [warn] Date and time set at power up + 00:00:04 2023-12-13 22:11:52 [warn] HTTP client 192.168.178.40 login succeeded (session key 0) 2023-12-13 22:13:20 [warn] WiFi module started 2023-12-13 22:13:20 [warn] WiFi module started 2023-12-13 22:13:27 [warn] WiFi module is connected to access point lunipu24, IP address 192.168.178.86

That would happen if your config.g file takes almost 2 minutes to execute, which could happen if (for example) it tried to configure a CAN-connected expansion board but no board at that address was found. Once config.g has been completed, the WiFi module will begin its scan for known networks, and that scan should complete within about 10 seconds.

**Comment by Lino77** [comment]
@dc42 okay but the WiFi module does not start by itself, only after I enter M587 via USB

**Comment by rechrtb** [comment]
Hi @Lino77  just to clarify, this is on an MB6HC + Duet3 WiFi module?

**Comment by Lino77** [comment]
@rechrtb  

Yes

**Comment by rechrtb** [comment]
Hi @Lino77, since there is now a new release candidate, are you able to upgrade to that and see if the problem still persists?

**Comment by Lino77** [comment]
I will do it and report

**Comment by Lino77** [comment]
okay RC 5 works perfectly, the best in terms of WLAN

**Comment by rechrtb** [comment]
Hi @Lino77, since it seems to be working for you now, will close this issue again.
