### ISSUE TITLE
Duet3 Mini: allocate EXINT6 and EXINT9 to spi.cs1 and spi.cs2 so that an accelerometer can be connected to temp daughterboard connector

### ISSUE THREAD

**Issue by dc42** [dc42/RepRapFirmware#844]
EXINTs 6 and 9 are currently allocated to VBUS (PB06) and to the encoder push button (PB09) but we don't currently use either of them. If instead we allocate them to spi.cs1 (PD11) and spi.cs2 (PC07) then those pins could be used as inputs. Using spi.cs1 for the accelerometer INT output would facilitate the use of a common SPI accelerometer cable with Duet 3 and Duet 3 6HC/6XD.

Need to check that PC07 really does use EXINT9 in case it is a typo on the datasheet (it would be more obvious if it used EXINT7).

**Comment by dc42** [comment]
The EXINTs have been reassigned in RRF 3.5beta4 source and the corresponding pin capabilities updated. Still need to test EXINT9 on spi.cs2.

**Comment by T3P3** [comment]
Tested working well with 1m cable on mini 5+
