### ISSUE TITLE
SBC interface calls ExpressionParser::ParseUnsigned without catching exceptions

### ISSUE THREAD

**Issue by dc42** [dc42/RepRapFirmware#853]
### Duet Forum Discussion Thread

https://forum.duet3d.com/topic/32459/3-5-0-beta-3-set-var-arr-0-1-in-loop-leads-to-reset

### Firmware Version

RRF 3.5.0-beta.3

### Duet Web Control Version

3.5.0-beta.3

### Are you using a Single Board Computer (RaspberryPi) with your Duet?

- [ X] Yes I use a SBC.
- [ ] No I do not use a SBC.

At line 741 of file SbcInterface.cpp function ExpressionParser::ParseUnsigned is called, but there is no try..catch block surrounding this area of code, so any exceptions thrown by the parser will cause termination. The stack trace in the forum thread indicates that this happened. It is not clear why this example causes an exception to be thrown.

**Comment by chrishamm** [comment]
Fixed on the v3-chrishamm branch.
