### ISSUE TITLE
New PWM code in RRF 3.5 doesn't allow PWM frequencies as low as 3.4 did

### ISSUE THREAD

**Issue by dc42** [dc42/RepRapFirmware#854]
### Duet Forum Discussion Thread

https://forum.duet3d.com/topic/32487/3-5-0-beta-3-minimum-pwm-frequency

### What happened?

The minimum PWM frequency on the 6HC used to be about 1.6Hz on outputs that use the PWM peripheral. in 3.5.0-beta3 it is about 3Hz.

**Comment by dc42** [comment]
Implement a probably fix in CoreN2G.

**Comment by T3P3** [comment]
tested on mini 5+ with latest build. Using:
M950 P0 C"out5" Q1
then
M42 P0 S0.5
resulted in approx 1Hz flashing of LED connected to out5.

**Comment by dc42** [comment]
Unfortunately that's not a valid test, because the code change only affects boards using the SAM4E, SAME7x or SAM4S, and it only affects those output ports that use the PWM peripheral. For example, on the 6HC it affects laser/vfd, out5, out2, out8, out1, out0.

**Comment by T3P3** [comment]
OP on the forum has confirmed fixed

**Comment by Pourya-3deo** [comment]
I have the same issue, I need 10 hz frequency but the lowest I can get is 17.88 Hz, I used an oscilloscope to measure.

**Comment by dc42** [comment]
@Pourya-3deo that is a different issue, it's a limitation of the PWM-capable ports that are drive by a timer/counter.
