### ISSUE TITLE
Linux compile issue, irregular capitalization

### ISSUE THREAD

**Issue by marlovdm** [dc42/RepRapFirmware#86]
I'm trying to compile the firmware on a linux based laptop.
After a couple of hours of troubleshooting (i'm a newbie) i noticed Reprap.h was sometimes referred to as RepRap.h.
On windows this does not matter, however linux throws a load of erros.

**Comment by dc42** [comment]
If you let me know which files have the incorrect capitalization in the #include directive then I'll fix it.

**Comment by dc42** [comment]
I've corrected the capitalization of the file on github.

**Comment by marlovdm** [comment]
woah, that's fast.


________________________________
Van: dc42 <notifications@github.com>
Verzonden: donderdag 23 maart 2017 20:47
Aan: dc42/RepRapFirmware
CC: marlovdm; Author
Onderwerp: Re: [dc42/RepRapFirmware] Linux compile issue, irregular capitalization (#86)


I've corrected the capitalization of the file on github.

**Comment by marlovdm** [comment]
MassStorge.h suffers from the same problem.
"Libraties/FatFs/ff.h" does not exist, "Libraties/Fatfs/ff.h" does
Pins_radds.h is referred to as Pins_RADDS.h
With these last two corrected, i succesfully compiled for duet085 and radds.

**Comment by marlovdm** [comment]
closing issue

**Comment by dc42** [comment]
I've corrected the capitalisation of Pins_RADDS.h. MassStorage.h will be fixed at next commit.
