### ISSUE TITLE
[Bug]: config-override.g trailing zeros

### ISSUE THREAD

**Issue by AndyEveritt** [dc42/RepRapFirmware#863]
### Duet Forum Discussion Thread

https://duet3d.slack.com/archives/C058RRMVA0G/p1685432532176539

### Which Duet products are you using?

- [ ] Duet2-Wifi
- [ ] Duet2-Ethernet
- [ ] Duet Expansion Breakout Board
- [ ] Duex2
- [ ] Duex5
- [ ] Duet2-Maestro
- [ ] Maestro Dual Driver Expansion
- [X] Duet3-6HC
- [ ] Duet3-3HC
- [ ] Duet3-1XD
- [ ] Duet3-1LC
- [ ] Duet3-Tool Distribution Board
- [ ] Duet3-Mini5+
- [ ] Duet3-Mini2+
- [ ] Raspberry Pi or other SBC
- [ ] SmartEffector
- [ ] Magnetic Filament Sensor
- [ ] Laser Filament Sensor
- [ ] PT100 Daughterboard
- [ ] Thermocouple Daughterboard
- [ ] PanelDue
- [ ] Other
- [ ] None

### Firmware Version

3.5.0-b3

### Duet Web Control Version

3.5.0-b3

### Are you using a Single Board Computer (RaspberryPi) with your Duet?

- [X] Yes I use a SBC.
- [ ] No I do not use a SBC.

### What happened?

- Previous versions of RRF generated a config-override with trailing zeros
  - ![image](https://github.com/Duet3D/RepRapFirmware/assets/38423143/877a21ee-b2f7-43f8-88db-1c092fc61570)
- RRF3.5.0-b3 throws an error when reading this file
  - ![image](https://github.com/Duet3D/RepRapFirmware/assets/38423143/91a53f0d-f561-42e9-81af-51acbcba0fcf)
- All tool offsets are now assumed to be zero
- Using `M500 P10` sets all the offsets to zero
- Removing the trailing zeros allows the config-override to be read normally
  - ![image](https://github.com/Duet3D/RepRapFirmware/assets/38423143/9d41bcea-1c60-4479-a137-76ee9e099aa6)
- `M500 P10` generates a working file but the offsets need to be updated the first time as they will all be zero

**Comment by dc42** [comment]
The cause of the additional zeros written in G10 commands was fixed already in the RRF 3.5-dev source code and has been back-ported to 3.4-dev in readiness for the 3.4.6 release. The additional checks performed by DSF 3.5.0-beta.3 have been relaxed in 3.5.0-beta.4 so that the additional zeros no longer cause the command to be rejected.
