### ISSUE TITLE
Feature request: Diamond hotend

### ISSUE THREAD

**Issue by boelle** [dc42/RepRapFirmware#88]
if the support is not allready there then it would be nice to virtual extruders build in

also there should be a 5 in 1 out model of the diamond underway

**Comment by dc42** [comment]
It's already supported, and I am fairly sure it has been before Repetier and Marlin had mixing support. But we call them tools, not virtual extruders. See https://somei3deas.wordpress.com/2017/01/11/using-the-diamond-hotend-with-duetwifi/.

**Comment by boelle** [comment]
Thanks....

will have a look at the link. I think with 5 extruders its game over for 8 bit stuff :-D
