### ISSUE TITLE
Increase maximum port length from 50 to at least 60

### ISSUE THREAD

**Issue by chrishamm** [dc42/RepRapFirmware#881]
Under certain circumstances, RRF 3.4 and 3.5 don't allow four pins to be configured at once. See https://forum.duet3d.com/topic/32954/duet-2-wifi-voron-2-4-multiple-z-endstops-query/7?_=1689100174074. That's why we should increase it in 3.4.6-rc.2 and 3.5.0-rc.1.

**Comment by dc42** [comment]
Fixed in 3.5-dev today ready fore 3.5.0-rc.1.

**Comment by dc42** [comment]
Also fixed in 3.4-dev ready for 3.4.6-rc.2 or 3.4.6 stable.
