### ISSUE TITLE
FTP server doesn't support LIST -a nor does it return an error

### ISSUE THREAD

**Issue by dc42** [dc42/RepRapFirmware#882]
### Duet Forum Discussion Thread

https://forum.duet3d.com/topic/32956/ftp-does-not-properly-respond-to-list-a

### Which Duet products are you using?

- [ ] Duet2-Wifi
- [ ] Duet2-Ethernet
- [ ] Duet Expansion Breakout Board
- [ ] Duex2
- [ ] Duex5
- [ ] Duet2-Maestro
- [ ] Maestro Dual Driver Expansion
- [ ] Duet3-6HC
- [ ] Duet3-3HC
- [ ] Duet3-1XD
- [ ] Duet3-1LC
- [ ] Duet3-Tool Distribution Board
- [ ] Duet3-Mini5+
- [ ] Duet3-Mini2+
- [ ] Raspberry Pi or other SBC
- [ ] SmartEffector
- [ ] Magnetic Filament Sensor
- [ ] Laser Filament Sensor
- [ ] PT100 Daughterboard
- [ ] Thermocouple Daughterboard
- [ ] PanelDue
- [ ] Other
- [ ] None

### Firmware Version

3.5.0-beta.4

### Duet Web Control Version

3.5.0-beta.4

### Are you using a Single Board Computer (RaspberryPi) with your Duet?

- [ ] Yes I use a SBC.
- [X] No I do not use a SBC.

### What happened?

Some FTP servers support a non-standard extension "LIST -a" and some FTP clients try to use it. Unfortunately the RRF FTP server treats "-a" as the directory name but doesn't report an error when it is not found. It should return an error if the directory argument of the LIST command is not found.

**Comment by T3P3** [comment]
Closed as presumed fixed after no response from the original reporter on the forum.
