### ISSUE TITLE
Incorrect X carriage movement on IDEX when changing to tool 1

### ISSUE THREAD

**Issue by dc42** [dc42/RepRapFirmware#886]
### Duet Forum Discussion Thread

https://forum.duet3d.com/topic/32672/toolchange-position-in-rrf-3-5-beta-4

### Which Duet products are you using?

- [ ] Duet2-Wifi
- [ ] Duet2-Ethernet
- [ ] Duet Expansion Breakout Board
- [ ] Duex2
- [ ] Duex5
- [ ] Duet2-Maestro
- [ ] Maestro Dual Driver Expansion
- [ ] Duet3-6HC
- [ ] Duet3-3HC
- [ ] Duet3-1XD
- [ ] Duet3-1LC
- [ ] Duet3-Tool Distribution Board
- [X] Duet3-Mini5+
- [ ] Duet3-Mini2+
- [ ] Raspberry Pi or other SBC
- [ ] SmartEffector
- [ ] Magnetic Filament Sensor
- [ ] Laser Filament Sensor
- [ ] PT100 Daughterboard
- [ ] Thermocouple Daughterboard
- [ ] PanelDue
- [ ] Other
- [ ] None

### Firmware Version

3.5beta4

### Duet Web Control Version

3.5beta4

### Are you using a Single Board Computer (RaspberryPi) with your Duet?

- [ ] Yes I use a SBC.
- [X] No I do not use a SBC.

### Details specific to your printer.

IDEX machine using two Duet 3 Mini boards (one in expansion mode).

### What happened?

After homing the X carriage (which contains the Z probe) is left at X160. When T1 is selected, the X carriage moves near to its home position to make way for the U carriage; however the X carriage subsequently trues to move back to X160, crashing into the U carriage. Worked OK in 3.4.5.

Reproduced by DC on a similar bench setup.

**Comment by dc42** [comment]
This issue is triggered by the combination of having tools with different axis mapping (i.e. X is mapped to U when using tool 1) and having movement in the tpre file. After running tfree (if a tool is being released) the current machine coordinates of owned are saved, then those axes that will not be owned by the new tool are released. However, if the tpre file then moves these axes again, the new coordinates were not saved and the axes released prior to selecting the new tool.

Fixed by moving the code that saves coordinates and releases axes until after tpre has been run, immediately prior to selecting the new tool.

**Comment by benecito** [comment]
Appears to be working now.
