### ISSUE TITLE
Potential bug in filament monitor connected to a main board used in expansion mode.

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#889]
Forum post:
https://forum.duet3d.com/topic/31001/magnet-filament-monitor-v4-calibration-issue/2

Requires reproducing.

**Comment by dc42** [comment]
Postponed until 3.5.0-rc.2

**Comment by dc42** [comment]
Filament monitors connected to main boards used as expansion boards did not work at all. I have fixed this in the 3.5-dev source code and tested the fixes, ready for rc2.
