### ISSUE TITLE
Delta forcing head into bed consistently while printing this object, no obvious G-code error

### ISSUE THREAD

**Issue by Djhg2000** [dc42/RepRapFirmware#89]
I'm trying to print a carriage adapter for my Kossel, but every time I try it always decides to force the head into the bed hard seemingly at a layer transition. It seems to be very sure of the move because it's pressing down hard enough to punch a hole through the object and skip steps for a second. Heck, it ever tore a hole though my blue painters tape last time.

I've attached both the G-code generated by Slic3r (head crashes around the layer 6 to 7 transition) and the STL generated by OpenSCAD. Other models print just fine and I've gone through the G-code manually by inspecting every G1 move with a Z parameter, all of those appear normal and are progressively telling the head to move up as far as I can tell.

It has taken me some time to report this because I was convinced it was a Slic3r bug and spent days, spread out across several months, trying to figure out what it is doing wrong. I first say this error about half a year ago but the earliest firmware version affected by this I can remember is 1.15e. At some point I tried a firmware upgrade from an earlier version when this first occurred, possibly from the 1.12 branch.

I'm not sure how to debug this and I have limited time to work on my printer at the moment but I'll provide any help I can to locate this bug.

[carriage_adapter_20x20_M3_v2_02mm_PLA.gcode.txt](https://github.com/dc42/RepRapFirmware/files/866356/carriage_adapter_20x20_M3_v2_02mm_PLA.gcode.txt)
[carriage_adapter_20x20_M3_v2.stl.txt](https://github.com/dc42/RepRapFirmware/files/866357/carriage_adapter_20x20_M3_v2.stl.txt)

**Comment by dc42** [comment]
Please raise this in the support forum at duet3d.com. If/when this becomes a confirmed firmware issue then it can be re-opened here.
