### ISSUE TITLE
Using a Scanning Analog Z probe as a normal Z probe

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#894]
Most work is already done for this, see:
https://github.com/Duet3D/RepRapFirmware/issues/615

One further job is to set the trigger threshold to be updated by M558.2 and any change to the trigger threshold via M558.2 or G31 should update the remote device.

**Comment by dc42** [comment]
Postponed until 3.5.0-rc.2

**Comment by dc42** [comment]
Believed complete in 3.5.0
