### ISSUE TITLE
Feature request: Extend M122 Pnnn to generate tests for all event types

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#895]
In order to test event handling macros it would be useful to have a P parameter, similar to M122 P109 that generates each of the event types. This could either be, for example P110  for filament-error P111 for driver-warning etc or MP110 S"driver-warning" etc Ideally the D, P,C parameters, if applicable, could be passed as well to specify the source and type of sub-event

**Comment by dc42** [comment]
Is https://docs.duet3d.com/User_manual/Reference/Gcodes#m957-raise-event not sufficient?

**Comment by T3P3** [comment]
Yes it is, I will make it more obvious in the event documentation that this feature exists.

**Comment by T3P3** [comment]
documentation updated
