### ISSUE TITLE
Redirect volume OM queries to SBC in SBC mode

### ISSUE THREAD

**Issue by chrishamm** [dc42/RepRapFirmware#906]
PanelDue does not display USB drives in SBC mode because it queries the "volumes" key from RRF, which is handled by DSF in SBC mode. Hence, the corresponding code M409 or OM query needs to be treated by DSF as well.

**Comment by T3P3** [comment]
Related to:
https://github.com/Duet3D/RepRapFirmware/issues/864
As thats another example of Object model information on the SBC needing to be available to RRF

**Comment by chrishamm** [comment]
`volumes` and `network` requests are handled by DSF already, see also 859ad64e2
