### ISSUE TITLE
M591 output truncated

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#908]
as reported here:
https://forum.duet3d.com/topic/33455/truncated-m591-response-in-console

I have confirmed the message is truncating
![image](https://github.com/Duet3D/RepRapFirmware/assets/1642947/c1a82a68-2835-40b0-9377-67e082f751e1)

**Comment by dc42** [comment]
According to https://forum.duet3d.com/post/325596 this issue affects RRF 3.4.6 too.

**Comment by dc42** [comment]
We do not plan to do any further 3.4.x releases.
