### ISSUE TITLE
MFM attached to Duet 3 Mini stops working in 3.5rc1

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#920]
Reported by OEM  (CR3D) and on forum:
https://forum.duet3d.com/topic/33822/filament-monitor-not-working

**Comment by dc42** [comment]
Fixed various issues with MFMs (they were not working at all when a main board was used as an expansion board, however the customer reports that the issue remains. New firmware build with additional diagnostics made available to customer.

**Comment by dc42** [comment]
The particular issue is that some time into the print, the filament monitor stops accumulating total extrusion and stops comparing measured vs. accumulated extrusion. The M122 report shows that data reception errors have occurred; whereas on my delta that uses a MFM attached to a Duet 3 Mini, the filament monitor doesn't stop working and I see no data reception errors. So perhaps the issue is failure to recover from a data reception error.

**Comment by dc42** [comment]
I asked for two M122 and M409 reports to be taken after the filament monitor stop accumulating extrusion, a few minutes apart.

Reports received 31 Oct 23 show:
 totalExtrusion in the OM: stuck at 206.9
 first M122: Extruder 0: pos 13871.95, errs: frame 0 parity 2 ovrun 0 pol 2 ovdue 0
 second M122 (2min 51sec later): Extruder 0: pos 13907.81, errs: frame 2 parity 2 ovrun 0 pol 3 ovdue 0.

Reports received 2 nov 23 show:
 totalExtrusion: stuck at 225.6
 first M122: check 5724205 clear 0 Extruder 0: pos 2318.20, errs: frame 9 parity 0 ovrun 0 pol 3 ovdue 0
 second M122 (1min 12sec later): check 5943297 clear 0 Extruder 0: pos 13902.19, errs: frame 9 parity 0 ovrun 0 pol 3 ovdue 0

Reports received 5 nov 23:
 totalExtrusion: stuck at 195.4
First M122: in 6243 notIn 1244232 Extruder 0: pos 13927.50, errs: frame 3 parity 0 ovrun 0 pol 1 ovdue 0
Second M122 (28 sec later):  in 6871 notIn 1330416 Extruder 0: pos 13950.70, errs: frame 3 parity 0 ovrun 0 pol 1 ovdue 0

**Comment by dc42** [comment]
Report received 17nov23:
1st M122 at 08:06:09 : in 9299 notIn 2121025 Extruder 0: pos 14024.88, debug 9269 8603 8498 7908 -174530.66, errs: frame 32 parity 0 ovrun 0 pol 6 ovdue 0
2nd M122 at 08:13:45: in 19430 notIn 3439590 Extruder 0: pos 13997.11, debug 19401 18734 18502 17410 -173350.59, errs: frame 32 parity 1 ovrun 0 pol 8 ovdue 0

The meaning of the debug output is:
Completed packets received, number of position reports received, number of position reports received with sync at the start bit, number of position reports received with sync at the start bit and >0.01mm extrusion, amount of extrusion commanded in the current segment. So it appears that RRF thinks there has been a very large (174m) negative amount of extrusion commanded and it is waiting for the extrusion to go positive before it compares again.

**Comment by dc42** [comment]
Found and fixed the cause of this issue. When 2 or more steps were scheduled to occur after the nominal end time of a move, a step error was logged. As part of this a value of 120000 was added to nextStep to indicate the cause f the step error when debugging was enabled. Doing this caused the filament monitor to consider that there had been a large amount of negative extrusion commanded, and it was waiting for this "retraction" to be undone before comparing again. A new firmware build has been made available to the custom for testing.
