### ISSUE TITLE
bed.g ignores Y maxima setting from config.g

### ISSUE THREAD

**Issue by croadfeldt** [dc42/RepRapFirmware#93]
Created a bed.g for my printer today, had a typo of Y1291 for one of the probe points. During bed compensation routine, the printer gleefully attempted to fulfill my request of Y1291 when Y maxima was set via M208 Y305. Details below

bed.g
G30 P1 X45 Y1291 Z-99999

config.g
M208 X326 Y305 Z635

**Comment by dc42** [comment]
I'm not sure this is really a bug because basically, we expect users to get their configuration files right. There are situations in which probing outside the normal printable area is desirable, for example when probing opposite the towers of a delta printer.

**Comment by croadfeldt** [comment]
Fair enough, k, I will close this then. Thanks Dave!
