### ISSUE TITLE
[FeatureRequest]: Configurable multiplier for fan speed.

### ISSUE THREAD

**Issue by JanJoh** [dc42/RepRapFirmware#946]
### Is your feature request related to a problem? Please describe.

Ex. I'm always frustrated when...
The current Tacho implementation assumes "Intel spec" fans, that is "two pulses per rotation". There are cases when this is not accurate. 

I, for instance, have a CPAP-style blower that has a 1Hz = 60rpm mapping on the speed pulse pin.

### Describe the solution you propose.

Ex. It would be definitely not essential but sort of nice if... we could get a parameter to configure this as described by
dc42 in a forum  https://forum.duet3d.com/topic/34694/multiplier-for-fan-speed?_=1705481829648

### Describe alternatives you've considered

Ex. A workaround exists but it is tedius, for example...

### Provide any additional context or information.

Ex. Photos, mockups, etc.

**Comment by dc42** [comment]
Completed.
