### ISSUE TITLE
Support the LIS2DW12 is 3.4.x

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#956]
The Duet 3 Accelerometer from v1.0 uses this.

**Comment by dc42** [comment]
I've cherry picked the relevant commits from RRF and CANlib 3.5-dev to 3.4-dev. The RRF 3.4 binaries build OK but I have not tested them. I have not back-ported the corresponding changes in Duet3Expansion, but that should not matter unless we do a version of the TOOL1LC board that uses the LIS2DW and we want to support 3.4 on it.

**Comment by dc42** [comment]
Implemented in 3.5-dev and 3.6-dev.

**Comment by dc42** [comment]
We are not planning any further 3.4.x releases.
