### ISSUE TITLE
Resuming after power failure - strange behavior

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#957]
As described here

https://forum.duet3d.com/topic/34927/resuming-after-power-failure-strange-behavior-arrays

**Comment by dc42** [comment]
I think it likely that this has been fixed in 3.5 rc4 and later. I have replied to the forum thread askeing the user to re-test using the 3.5.1 release.

**Comment by T3P3** [comment]
Closing, will reopen if the user reports an ongoing issue.
