### ISSUE TITLE
M587/588 do not check the WiFi mode creating potential SPI Timeout errors

### ISSUE THREAD

**Issue by chrishamm** [dc42/RepRapFirmware#960]
M587 and possibly M588 do not check the current WiFi mode, so while the module is changing its mode and a user attempts to use one of these commands, `SPI Timeout` errors can be seen. This can be troublesome at least when upgrading from 1.27 to  2.1beta6 with a broken SPIFFS partition. Current work-around for that scenario:

```
Run M552 S0 first, wait for the Error: WiFi module reported: no known networks found to stop, M588 S"*", M587 the credentials, and then M552 S1
```

This scenario happened with RepRapFirmware 3.5.0-rc.3.

**Comment by dc42** [comment]
Fixed in 3.5-dev source.
