### ISSUE TITLE
M208 machine axis limits not honoured when axes are mapped

### ISSUE THREAD

**Issue by dc42** [dc42/RepRapFirmware#976]
We have a report that when an IDEX machine is used with a Copy tool, machine axis limits are not honoured. See https://forum.duet3d.com/topic/35433/3-5-0-rc4-weird-homing-behaviour-in-idex-copy-or-mirror-mode.

**Comment by dc42** [comment]
Changed the axis limit check in 3.5.1 for straight moves to check axes after tool XYZ axis mapping is done. Still need to test this and implement it for G2/G3 moves. We should also look at changing G2/G3 to check the entire move at the start for exceeding axis limits, using the same code that we do in keepout zones.

**Comment by T3P3** [comment]
outstanding G2/G3 work moved to  #1062
