### ISSUE TITLE
MessageFormats.h missing

### ISSUE THREAD

**Issue by dnewman-polar3d** [dc42/RepRapFirmware#98]
Referenced in `src/DuetNG/DuetWiFi/Network.h`.  Kind of stops the compilation in its tracks.

**Comment by dc42** [comment]
To build DuetWiFiFirmware 1.19 you need to add project DuetWiFiSocketServer to the Eclipse workspace.

**Comment by dnewman-polar3d** [comment]
Sort of okay.  Looks like `MessageFormats.h` is out of date? 

`DuetNG/DuetWiFi/Network.cpp`
1. Uses a field named "protocol" in the ListenOrConnectData structure.  However, the present MessageFormats.h doesn't declare that field in that structure.
2. Expects a "diagnostics" value in the enum NetworkCommand.  However, the present MessageFormats.h doesn't declare that value in that enum.
