### ISSUE TITLE
FTP connexion

### ISSUE THREAD

**Issue by Lepterois** [dc42/RepRapFirmware#99]
Hi!
I've done the firmware update to the 1.18.1 on my Ormerod2. Since this update I cannot connect anymore to my Ormerod in FTP using Filezilla.
What can I do for this? before I used Version 1.09 and it was working fine. What is changing between the 2 versions?

Thanks in advance

**Comment by dc42** [comment]
Read the upgrade notes in the WHATS_NEW file in github.

**Comment by Lepterois** [comment]
thanks for reply.
the history I found stop at 1.16 version and I was at version 1.09 ;-)
and that's like chinese for me lol
but I get the answer somewhere else
regards

**Comment by dc42** [comment]
https://github.com/dc42/RepRapFirmware/blob/dev/WHATS_NEW.md

**Comment by Lepterois** [comment]
Thanks very much.
this link is very interesting!
