### ISSUE TITLE
Further restrict what gcodes can be run after M112

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#992]
As at RRF 3.5.1 the spindle control commands can be run after the M112 command. These should be restricted until the board is reset.

Potentially restrict the commands that can be run after M112 to the following:
M999
M122
M409

**Comment by jesse-stojan** [comment]
It is absolutely necessary that Emergency Stop not permit further motor controls until reset/unlocked, as it helps bring RRF into compliance with safety standards and codes that are currently in violation of IEC, NEC, ANSI, and OSHA codes.

**Comment by dc42** [comment]
Implemented in 3.5-dev. Only the following commands can be run after M112: M105 M112 M115 M122 M408 M409 M999.
