### ISSUE TITLE
[FeatureRequest]: Label the 4 values in the M558.1 report

### ISSUE THREAD

**Issue by droftarts** [dc42/RepRapFirmware#999]
Sending `M558.1 K1` after calibrating a scanning Z probe reports:
```
M558.1 K1
Scanning probe coefficients [1.840e-1, -2.865e-4, 2.598e-10, 2.937e-17]
```
The first coefficient is the difference in reading from the target reading at the trigger height during calibration, and automatically generated.
The second coefficient is the linear coefficient of the output and is M558.1 A parameter.
The third coefficient is the quadratic coefficient of the output and is M558.1 B parameter.
The fourth coefficient is the cubic coefficient of the output and is M558.1 C parameter.

Add labels to the M558.1 K1 output to make this clearer, eg
```
M558.1 K1
Scanning probe coefficients [offset 1.840e-1, A -2.865e-4, B 2.598e-10, C 2.937e-17]
```

**Comment by dc42** [comment]
Fixed in 3.6-dev and back-ported to 3.5-dev.
